import { PrismaClient } from '@prisma/client';

// =============================================================================
// Seed 25: Expanded Personalized Insights — Astellas Pharma Inc. (OTC: ALPMY)
// ~55 insights covering FY25 results, XTANDI IRA risk, PADCEV growth,
// Strategic Brands launch momentum, SMT transformation, FX exposure,
// Japan NHI pricing, China NRDL expansion, R&D pipeline, and capital allocation.
//
// PersonalizedInsight model:
//   companyId, title, category, insightLevel, metricId, kpiValue,
//   trendDirection, priority, summary, confidenceScore, consoleLink,
//   recommendations (JSON), relatedDrivers (JSON)
// =============================================================================

export async function seedExpandedInsights(prisma: PrismaClient, companyId: number) {
  console.log('  Seeding Astellas Pharma expanded insights (~55 records)...');

  const insights = [

    // =========================================================================
    // CORE EPS AND FINANCIAL PERFORMANCE (8 insights)
    // =========================================================================
    {
      title: 'FY25 Core EPS ¥237.01 — +49.8% YoY; Best Growth in Five Years',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Core EPS',
      kpiValue: '¥237.01 FY25 Core EPS vs ¥158.24 FY24 (+49.8% YoY)',
      trendDirection: 'up',
      priority: 'critical',
      summary: 'Astellas Core EPS of ¥237.01 in FY25 grew +49.8% year-over-year — the strongest EPS growth in five years — driven by SMT savings delivery (¥21B, ¥3B above plan), VEOZAH launch outperformance (¥87.3B vs. ¥72B plan), and a ¥158 → ¥237 trajectory reflecting both operational leverage and portfolio mix shift. The 49.8% growth partially reflects FY24 one-time restructuring charges normalising out of the base, but core operational improvement contributed approximately 25–28% organic EPS growth. FY26 guidance of ¥248–¥255 (+5–7%) implies continued but more moderate growth as IRA MFP impacts on XTANDI begin.',
      confidenceScore: 0.97,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Communicate FY24-to-FY25 EPS bridge clearly: restructuring normalisation vs. operational improvement vs. SMT vs. portfolio — analysts need the decomposition to model FY26',
        'Provide quarterly Core EPS guidance sensitivity: each ¥1 USD/JPY move = ¥0.9 Core EPS impact; each 1pp IRA price cut = ¥4.1 Core EPS impact',
        'Disclose SMT savings trajectory quarterly to maintain confidence in the ¥40B FY26 / ¥65B cumulative targets',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core EPS', impact: '¥237.01 FY25, +49.8% YoY; FY26 guidance ¥248–¥255', trend: 'positive' },
        { driver: 'SMT Savings', impact: '¥21B delivered FY25; primary EPS growth driver', trend: 'positive' },
        { driver: 'VEOZAH Revenue', impact: '¥87.3B vs ¥72B plan; launch outperformance adds to mix', trend: 'positive' },
      ]),
    },
    {
      title: 'Core OP Margin 26.0% FY25 — At Guidance; SMT Driving Toward 27-28% FY26 Target',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Core OP Margin',
      kpiValue: '26.0% FY25 Core OP Margin; FY26 target 27-28%',
      trendDirection: 'up',
      priority: 'high',
      summary: 'FY25 Core OP margin of 26.0% was in line with the 25.5–26.5% guidance range. Quarterly variation was significant: Q1 24.3% (launch investment), Q2 25.8%, Q3 32.8% (milestone payment and SMT acceleration), Q4 21.2% (NHI accrual and launch costs). The FY26 management target of 27–28% core margin requires ¥40B SMT savings delivery and PADCEV/Strategic Brands mix-shift contribution to offset XTANDI IRA headwind. SG&A ratio improvement from 40.2% to sub-39% is the key operating lever. R&D investment is expected to hold at ~14.6% of revenue.',
      confidenceScore: 0.90,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Frame quarterly margin volatility clearly for investors — Q3 spike and Q4 trough are structural, not trend signals',
        'Provide SMT savings-to-margin conversion ratio: ¥1B savings = approximately 4–5bps margin improvement at current revenue base',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core OP Margin', impact: '26.0% FY25; SMT drives toward 27-28% FY26', trend: 'positive' },
        { driver: 'SMT Savings', impact: 'Primary lever for margin expansion', trend: 'positive' },
      ]),
    },
    {
      title: 'Q1 FY25 Core OP Margin 24.3% — Below Annual Average; Launch Investment Quarter',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'Core OP Margin',
      kpiValue: '24.3% Q1 FY25 Core OP Margin (below 26.0% FY25 average)',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Q1 FY25 Core OP margin of 24.3% was 170bps below the full-year average, reflecting front-loaded selling and marketing investment for VYLOY (gastric cancer) and IZERVAY (geographic atrophy) global launches totalling approximately ¥8.5B above the Q1 plan. This launch investment drag is temporary: revenue from these products ramps through Q2–Q4 FY25 while the cost spike was concentrated in Q1. PADCEV and XTANDI underpinned underlying profitability. The Q1 margin trough is consistent with Astellas\'s pattern of front-loading commercial investment in new fiscal years.',
      confidenceScore: 0.92,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Pre-communicate Q1 launch investment cadence to prevent margin miss interpretation as structural deterioration',
        'Monitor VYLOY and IZERVAY new patient starts weekly in Q1 to validate the investment-to-return conversion timeline',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core OP Margin', impact: 'Q1 24.3% reflects launch investment; recovers Q2+', trend: 'neutral' },
        { driver: 'VYLOY Revenue', impact: 'Launch investment front-loaded to Q1', trend: 'neutral' },
      ]),
    },
    {
      title: 'FY25 Total Revenue ¥2,139.2B — In Line with Guidance; +4.5% Volume Growth Offset FX Headwind',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Total Revenue',
      kpiValue: '¥2,139.2B FY25 Revenue; +4.5% volume growth, -1.8% FX headwind',
      trendDirection: 'up',
      priority: 'high',
      summary: 'FY25 Revenue of ¥2,139.2B was within the ¥2,100–¥2,160B guidance range. Volume growth of +4.5% (driven by PADCEV +34.8%, VEOZAH +188%, China +29.6%) was partially offset by a -1.8% FX headwind (average USD/JPY ¥149.8 vs. ¥151 budget). Japan NHI revision contributed -¥7.8B headwind. Net price realisation was -0.6% as mandatory NHI discounts and IRA pre-positioning were partially offset by new product pricing. FY26 revenue guidance of ¥2,200–¥2,260B (+3–6%) reflects continued Strategic Brands volume growth and partial IRA impact.',
      confidenceScore: 0.94,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Decompose revenue growth drivers: volume, price, FX, and mix — quarterly disclosure helps model FY26 under different rate scenarios',
        'Highlight Strategic Brands growing from 18% to 22% of revenue — portfolio diversification narrative is compelling for investors',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Total Revenue', impact: '¥2,139.2B FY25; volume +4.5%, FX -1.8%', trend: 'positive' },
        { driver: 'PADCEV Revenue', impact: '¥221.2B, +34.8% YoY — largest volume contributor', trend: 'positive' },
      ]),
    },
    {
      title: 'Q3 FY25 Core OP Margin 32.8% — Structural High; Royalty Milestone and SMT Front-Loading',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'Core OP Margin',
      kpiValue: '32.8% Q3 FY25 Core OP Margin — highest quarterly reading in 5 years',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'Q3 FY25 Core OP margin of 32.8% was 530bps above the full-year average and the highest quarterly margin in five years. Three concurrent factors drove the Q3 spike: (1) ¥8.5B royalty milestone from the Pfizer XTANDI co-promotion agreement; (2) SMT savings acceleration with Phase 1 procurement savings front-loaded to Q3; and (3) R&D spend below plan as Phase 3 trials enrolled faster than expected in Q2. The 32.8% Q3 margin is not a run-rate — Q4 FY25 normalised to 21.2%. Full-year 26.0% is the relevant benchmark.',
      confidenceScore: 0.93,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Clearly label Q3 margin spike drivers in earnings materials to prevent run-rate over-extrapolation',
        'Royalty milestone timing should be disclosed to avoid Q4 miss interpretation when margins normalise',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core OP Margin', impact: 'Q3 32.8% spike; full-year 26.0% is the benchmark', trend: 'positive' },
        { driver: 'SMT Savings', impact: 'Phase 1 savings front-loaded to Q3', trend: 'positive' },
      ]),
    },
    {
      title: 'Free Cash Flow FY25 ¥520.8B — Above ¥498B Plan; Working Capital and SMT Driving Cash Generation',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Operating Cash Flow',
      kpiValue: '¥520.8B FY25 FCF vs ¥498B plan (+4.6%); net cash position +¥82B',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Free cash flow of ¥520.8B exceeded plan by ¥22.8B, driven by accelerated US managed care rebate receivables collection (¥8.5B), SMT personnel savings cash flow (¥5.2B), and ¥9.1B capex below plan (Yamaguchi manufacturing expansion phased over two years). Operating cash conversion of 93.7% (FCF/Core Net Income) demonstrates strong balance sheet quality. The net cash position improved to +¥82B at FY25 year-end, enabling the ¥78/share full-year dividend (¥139.7B) and a ¥50B share buyback programme announced in March 2026.',
      confidenceScore: 0.93,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Highlight FCF/EPS conversion ratio in investor materials — the ¥520.8B FCF vs. ¥424.6B Core Net Income represents strong cash quality',
        'Communicate capital allocation priority order: dividend maintenance → share buyback → strategic M&A optionality',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Operating Cash Flow', impact: '¥520.8B FCF; net cash +¥82B', trend: 'positive' },
        { driver: 'SMT Savings', impact: 'Cash savings ahead of P&L recognition', trend: 'positive' },
      ]),
    },
    {
      title: 'Core Revenue FY25 ¥2,139.2B — Geographic Mix Shift: US 44%, EM 26%, Japan 14%, Intl 11%, China 5%',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'Total Revenue',
      kpiValue: 'FY25 geographic mix: US 44%, EM 26%, Japan 14%, International 11%, China 5%',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Astellas revenue geographic mix is evolving: China grew from 4% to 5% of revenue (¥101.5B, +29.6% YoY), while Japan declined from 15% to 14% due to NHI pricing. The US remains dominant at 44% (¥940.2B) — both a strength (XTANDI market position) and a concentration risk (IRA). Established Markets stability at 26% (¥563.6B) reflects PADCEV and VEOZAH European launch contribution offsetting mature product erosion. International Markets at 11% (¥230.7B) represent the highest growth optionality segment for XTANDI ex-OECD and emerging market PADCEV launches.',
      confidenceScore: 0.96,
      consoleLink: '/business-consoles/americas-performance',
      recommendations: [
        'Frame geographic diversification progress: US % of revenue declining from 46% to 44% FY24-FY25 reduces IRA concentration risk',
        'China growing to 5% of revenue and targeting ¥150B in FY26 is an underappreciated growth catalyst',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'United States Revenue', impact: '44% of FY25 total; IRA concentration risk', trend: 'neutral' },
        { driver: 'China Revenue', impact: '5% of total, +29.6% YoY; fastest growing segment', trend: 'positive' },
      ]),
    },
    {
      title: 'ROE 17.4% FY25 — Improvement from 11.2% FY24; SMT and EPS Growth Driving Return Expansion',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'Core EPS',
      kpiValue: 'ROE 17.4% FY25 vs 11.2% FY24; driven by Core Net Income +49.8%',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'Return on equity improved from 11.2% in FY24 to 17.4% in FY25, primarily driven by Core Net Income growth of +49.8% YoY. Equity base grew modestly (+4.2%) as dividend payments and share buybacks partially offset retained earnings accumulation. The ROE improvement signals that Astellas\'s portfolio transformation and SMT cost programme are delivering returns above the cost of equity (estimated at 8–9%). FY26 ROE target of 18–19% assumes Core EPS of ¥248–¥255 and continued capital returns via dividends and buybacks.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Include ROE trajectory in shareholder letter and investor presentations as evidence of capital allocation effectiveness',
        'Benchmarking Astellas ROE vs. pharma peers (AstraZeneca ~25%, Pfizer ~30%) helps contextualise improvement path',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core EPS', impact: '+49.8% drives ROE from 11.2% to 17.4%', trend: 'positive' },
        { driver: 'SMT Savings', impact: 'Cost reduction improves asset productivity', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // XTANDI / IRA RISK MANAGEMENT (7 insights)
    // =========================================================================
    {
      title: 'XTANDI IRA MFP Risk — ¥9.6B Core OP Impact per 1pp Price Cut; FY26 Guidance Already Incorporates',
      category: 'Risk & Compliance',
      insightLevel: 'L1',
      metricId: 'XTANDI Revenue',
      kpiValue: '¥9.6B Core OP sensitivity per 1pp IRA price reduction; FY26 guidance range reflects disclosed MFP',
      trendDirection: 'down',
      priority: 'critical',
      summary: 'XTANDI (enzalutamide) was selected for IRA Maximum Fair Price (MFP) negotiation effective January 1, 2026. Astellas and Pfizer have disclosed a ¥9.6B annual Core OP sensitivity per 1 percentage point of net price reduction. With XTANDI representing approximately 45% of Astellas FY25 Core Revenue (¥960.8B), the MFP negotiation is the single largest financial risk event in the near-term plan. Management has incorporated the disclosed MFP outcome into FY26 guidance (¥248–¥255 Core EPS), and SMT savings (¥40B FY26 target) serve as the primary financial offset. The IRA impact applies directly to Medicare Part D claims (~28–32% of XTANDI US volume); commercial payer reference pricing creates additional but harder-to-quantify downside.',
      confidenceScore: 0.91,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Maintain quarterly IRA scenario disclosure: base (disclosed MFP), adverse (+2pp above MFP from commercial reference), and upside (volume preservation strategies)',
        'Quantify XTANDI non-US revenue as the IRA-independent portion — ex-US XTANDI is approximately 55% of total and not subject to MFP',
        'Link SMT savings delivery explicitly to XTANDI IRA mitigation in all investor communications',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: '¥9.6B/1pp sensitivity; FY26 guidance incorporates MFP', trend: 'negative' },
        { driver: 'Core EPS', impact: '¥4.1/share sensitivity per 1pp IRA price cut', trend: 'negative' },
        { driver: 'SMT Savings', impact: '¥40B FY26 target as primary financial offset', trend: 'positive' },
      ]),
    },
    {
      title: 'XTANDI FY25 Revenue ¥960.8B — Largest Astellas Product at 44.9% of Total; Market Share 48.2%',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'XTANDI Revenue',
      kpiValue: '¥960.8B FY25 XTANDI Revenue; 48.2% ARSi market share',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'XTANDI remains Astellas\'s dominant revenue contributor at ¥960.8B (44.9% of FY25 Core Revenue). US market share in the androgen receptor signalling inhibitor (ARSi) class is 48.2%, with ERLEADA and darolutamide as the primary competitors. International markets (non-US) account for approximately 55% of XTANDI revenue, providing significant IRA-independent earnings protection. The FY25 XTANDI revenue was broadly stable YoY (modest volume growth offset by net price erosion and FX headwinds). The strategic priority for FY26–FY27 is preserving volume share as IRA price awareness potentially influences prescriber behaviour.',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Accelerate XTANDI non-US market development — Brazil, ANZ, South Korea market access wins highlight the international volume optionality',
        'Invest in XTANDI real-world evidence programmes to defend clinical differentiation vs. ERLEADA and darolutamide in key academic centres',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: '¥960.8B FY25; 44.9% of total revenue', trend: 'neutral' },
        { driver: 'XTANDI US Market Share', impact: '48.2% ARSi share; IRA awareness minor headwind Q1 FY26', trend: 'negative' },
      ]),
    },
    {
      title: 'XTANDI International Revenue — 55% of Total; Brazil/ANZ/Korea Access Wins Reducing IRA Dependency',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: '~55% of XTANDI revenue from ex-US markets; not subject to IRA MFP',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Approximately 55% of XTANDI global revenue (approximately ¥528B) is generated outside the US and is not subject to IRA Maximum Fair Price negotiations. International XTANDI growth is accelerating: International Markets segment grew +22% YoY in Q1 FY25, driven by Brazil mCSPC reimbursement approval (February 2025), Australia/New Zealand PBS listing expansion, and South Korea hospital tender win. European markets maintained stable volume despite patent expiry preparations. Growing the non-US XTANDI contribution is a core strategic response to IRA risk — each percentage point of US-to-ex-US mix shift reduces IRA sensitivity by approximately ¥96M annually.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/international-asia-performance',
      recommendations: [
        'Disclose XTANDI US vs. ex-US revenue split quarterly — this transparency demonstrates IRA risk mitigation progress',
        'Prioritise access in top-10 ex-US markets: Germany, Japan, UK, France, Brazil, Australia, Spain, Canada, Italy, South Korea',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: '55% ex-US provides IRA diversification', trend: 'positive' },
        { driver: 'International Markets Revenue', impact: '+22% YoY Q1 FY25 driven by new access wins', trend: 'positive' },
      ]),
    },
    {
      title: 'XTANDI Competition — ERLEADA and Darolutamide Hold 38% Combined ARSi Share; Differentiation Critical',
      category: 'Competitive Intelligence',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'XTANDI 48.2% ARSi share vs. ERLEADA+darolutamide 38% combined; LYNPARZA competition in later lines',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'XTANDI faces competition from ERLEADA (apalutamide, J&J) and darolutamide (Bayer/Nurix) in the ARSi class for prostate cancer. ERLEADA holds approximately 24% ARSi share; darolutamide approximately 14%. XTANDI\'s market leadership reflects its earlier approval, broader label coverage (non-metastatic and metastatic CRPC and CSPC), and long-standing physician familiarity. IRA pricing awareness may slightly accelerate prescriber trial of alternatives — the ERLEADA/darolutamide competitive response is the primary concern if XTANDI net price perception changes materially. AstraZeneca/Merck\'s LYNPARZA (olaparib, PARP inhibitor) competes in the BRCA-mutated prostate cancer sub-population.',
      confidenceScore: 0.85,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Commission quarterly oncologist perception surveys to monitor IRA-awareness-driven prescribing behaviour shifts early',
        'Accelerate XTANDI real-world outcome studies vs. ERLEADA/darolutamide — the broader label coverage (all CSPC/CRPC lines) is XTANDI\'s key differentiator',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI US Market Share', impact: '48.2% vs. ERLEADA 24% + darolutamide 14%', trend: 'neutral' },
        { driver: 'XTANDI Revenue', impact: 'Competitive dynamics intensify post-IRA announcement', trend: 'negative' },
      ]),
    },
    {
      title: 'XTANDI SMT Offset Calibration — ¥40B FY26 SMT vs ¥9.6B IRA Impact; 4:1 Offset Ratio',
      category: 'Strategic Initiatives',
      insightLevel: 'L2',
      metricId: 'SMT Savings',
      kpiValue: '¥40B FY26 SMT target vs ~¥9.6B IRA impact; net ¥30B positive swing',
      trendDirection: 'positive',
      priority: 'high',
      summary: 'The SMT programme provides an approximately 4:1 offset ratio to the XTANDI IRA headwind: ¥40B FY26 SMT savings target vs. an estimated ¥9.6B IRA core OP impact (at the disclosed base MFP). Even in an adverse IRA scenario (2pp above base = ¥19.2B impact), SMT savings provide a >2:1 offset. This calibration explains management\'s confidence in maintaining FY26 Core EPS guidance despite IRA risk. The risk scenario is a combination of IRA adverse + SMT underdelivery — both simultaneously would breach the lower end of guidance.',
      confidenceScore: 0.87,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Present the SMT-vs-IRA offset explicitly in investor materials — the quantified buffer helps investors understand the earnings durability',
        'Disclose SMT savings by programme phase to allow investors to track delivery against the ¥40B target quarterly',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: '¥40B FY26 target; 4:1 offset vs. IRA ¥9.6B impact', trend: 'positive' },
        { driver: 'Core EPS', impact: 'SMT delivery is primary driver of FY26 EPS guidance confidence', trend: 'positive' },
      ]),
    },
    {
      title: 'XTANDI Q4 FY25 Quarterly Revenue ¥239.8B — Below Annual Run-Rate; Japan NHI and FX Headwinds',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'Q4 FY25 XTANDI ¥239.8B; Q1-Q4 FY25: ¥238.4, ¥240.1, ¥242.5, ¥239.8B',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'XTANDI quarterly revenue was broadly stable across FY25 (¥238–¥243B range), reflecting roughly equal contributions from volume growth and net price erosion in each quarter. The slight Q4 decline reflects: (1) Japan NHI Q4 accrual pre-revision adjustment and (2) unfavourable Q4 FX as JPY strengthened seasonally. The stable quarterly trajectory provides a clear FY26 baseline before IRA MFP impact. FY26 XTANDI revenue guidance assumes a modest mid-single-digit percentage decline in total XTANDI revenue vs. FY25, reflecting IRA US volume/price impact partially offset by continued international growth.',
      confidenceScore: 0.91,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Provide quarterly XTANDI guidance decomposition: US volume, US net price, ex-US volume, FX — enables more precise modelling',
        'Track XTANDI IRA patient access programmes quarterly to distinguish IRA-driven vs. competition-driven volume trends',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: 'Q4 FY25 ¥239.8B; stable quarterly range ¥238–¥243B', trend: 'neutral' },
        { driver: 'Japan Revenue', impact: 'NHI Q4 accrual creates seasonal headwind', trend: 'negative' },
      ]),
    },
    {
      title: 'XTANDI mCSPC Market Opportunity — New Indications Expanding Addressable Patient Population',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'mCSPC indication doubles addressable prostate cancer patient population vs. mCRPC alone',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'XTANDI\'s mCSPC (metastatic castration-sensitive prostate cancer) indication approval has approximately doubled the addressable patient population vs. the original mCRPC approval. Newly diagnosed mCSPC patients represent earlier treatment initiation (longer treatment duration), and the mCSPC patient population is estimated at 3–4x the mCRPC annual new patient cohort. XTANDI\'s FDA-approved label now covers mCRPC, nmCRPC, mCSPC, and nmCSPC — the broadest prostate cancer label among ARSi competitors. New indication capture is one of the strategies to offset volume per-patient price reduction from IRA MFP through treatment line expansion.',
      confidenceScore: 0.85,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Report XTANDI prescription volume by indication segment (mCRPC vs. mCSPC vs. nmCRPC vs. nmCSPC) — this granularity demonstrates the indication expansion strategy',
        'Quantify mCSPC label expansion contribution to XTANDI US volume growth to show the organic volume offset to price headwinds',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: 'mCSPC indication doubles addressable population', trend: 'positive' },
        { driver: 'XTANDI US Market Share', impact: 'Broadest prostate cancer label advantage', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // STRATEGIC BRANDS — PADCEV, VEOZAH, IZERVAY, VYLOY (9 insights)
    // =========================================================================
    {
      title: 'Strategic Brands FY25 ¥480.3B — +43% YoY; Growing from 18% to 22% of Revenue',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'Strategic Brands Revenue',
      kpiValue: '¥480.3B FY25 Strategic Brands (+43% YoY); 22% of total revenue vs. 18% FY24',
      trendDirection: 'up',
      priority: 'critical',
      summary: 'Strategic Brands combined revenue of ¥480.3B grew +43% YoY in FY25, increasing the portfolio\'s share of total revenue from 18% to 22%. PADCEV led growth (¥221.2B, +34.8%), followed by VEOZAH (¥87.3B, +188%), VYLOY (¥59.7B, launch year), and IZERVAY (¥52.1B, launch year). The portfolio mix shift reduces Astellas\'s XTANDI concentration from 46% to 45% of revenue and provides a structural hedge against IRA XTANDI risk. FY26 Strategic Brands target is ¥610–¥640B (+27–33%), driven by PADCEV first-line mUC ramp, VEOZAH payer coverage expansion to 70%+, and VYLOY NRDL ramp in China.',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Frame the Strategic Brands growth as both absolute performance AND portfolio risk reduction — the XTANDI concentration story is complementary',
        'Provide FY26 Strategic Brands revenue guidance with product-level breakdown to enable granular modelling',
        'Target Strategic Brands reaching 30%+ of total revenue by FY28 as the key long-term portfolio diversification milestone',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Strategic Brands Revenue', impact: '¥480.3B FY25, +43% YoY; 22% of total', trend: 'positive' },
        { driver: 'PADCEV Revenue', impact: '¥221.2B, +34.8%; dominant contributor', trend: 'positive' },
        { driver: 'VEOZAH Revenue', impact: '¥87.3B vs ¥72B plan; launch outperformance', trend: 'positive' },
      ]),
    },
    {
      title: 'PADCEV FY25 ¥221.2B — +34.8% YoY; First-Line mUC Expansion Driving Above-Market Growth',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'PADCEV Revenue',
      kpiValue: '¥221.2B FY25 PADCEV Revenue (+34.8% YoY); FY26 guidance ¥265–¥285B',
      trendDirection: 'up',
      priority: 'critical',
      summary: 'PADCEV (enfortumab vedotin + pembrolizumab) achieved ¥221.2B in FY25 — +34.8% YoY growth — as first-line urothelial carcinoma (mUC) prescriptions ramped following the CMS coverage determination in H2 FY24. EV-302 Phase 3 data presented at ESMO October 2025 confirmed PADCEV as the standard of care in first-line mUC, driving further adoption at academic oncology centres. Ex-US reimbursement decisions in Germany, UK, France, and Spain were received in Q1 FY25, accelerating European launch. Management raised FY26 PADCEV guidance to ¥265–¥285B — a further +20–+29% growth — based on first-line mUC patient volume ramp and pipeline combination study data.',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Provide PADCEV quarterly volume by line of therapy (first-line vs. second-line+) — market investors are acutely focused on first-line capture rate',
        'Report US vs. ex-US PADCEV revenue split quarterly to track European launch contribution',
        'Disclose PADCEV/pembrolizumab co-formulation development timeline — combination SKU simplification could enhance compliance',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'PADCEV Revenue', impact: '¥221.2B FY25 +34.8%; FY26 guidance ¥265–285B', trend: 'positive' },
        { driver: 'Strategic Brands Revenue', impact: 'PADCEV is the dominant Strategic Brands contributor', trend: 'positive' },
      ]),
    },
    {
      title: 'VEOZAH FY25 ¥87.3B — +188% YoY; Payer Coverage Inflection Driving Commercial Acceleration',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'VEOZAH Revenue',
      kpiValue: '¥87.3B FY25 VEOZAH Revenue (+188% YoY); 62% commercial payer coverage',
      trendDirection: 'up',
      priority: 'high',
      summary: 'VEOZAH (fezolinetant) revenue grew +188% YoY in FY25, reaching ¥87.3B vs. the ¥72B plan (+21% above). The non-hormonal NK3 receptor antagonist mechanism positions VEOZAH uniquely for women who cannot or prefer not to use hormone replacement therapy (HRT) — a meaningful segment of the estimated 50M menopausal women in the US with moderate-to-severe vasomotor symptoms. The commercial inflection came when payer formulary coverage crossed 50% (Q2 FY25) — prescribers reported confidence to prescribe when insurance reimbursement was confirmed. Coverage reached 62% at Q4 FY25 end, with a FY26 target of 70%+. VEOZAH is now the fastest-growing women\'s health pharmaceutical in the US market.',
      confidenceScore: 0.93,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Report VEOZAH payer coverage as a leading indicator KPI each quarter — the 50%→70% coverage journey is the primary driver of new patient starts',
        'Track DTC advertising conversion: cost per new patient start trending 15% below model is a strong efficiency signal',
        'Develop VEOZAH physician education programme for OBGYN offices that have not yet prescribed — 40%+ of reproductive health specialists have not initiated a VEOZAH patient',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'VEOZAH Revenue', impact: '¥87.3B FY25 +188%; 62% payer coverage reached', trend: 'positive' },
        { driver: 'Strategic Brands Revenue', impact: 'VEOZAH contributing 18% of Strategic Brands FY25', trend: 'positive' },
      ]),
    },
    {
      title: 'IZERVAY FY25 ¥52.1B — Geographic Atrophy Launch Year; Competing with Apellis Syfovre',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'Strategic Brands Revenue',
      kpiValue: '¥52.1B IZERVAY FY25 (launch year); geographic atrophy market ~$2B US addressable',
      trendDirection: 'up',
      priority: 'high',
      summary: 'IZERVAY (avacincaptad pegol) achieved ¥52.1B in its first full commercial year for geographic atrophy (GA) — a progressive retinal disease causing central vision loss. IZERVAY competes with Apellis\'s Syfovre (pegcetacoplan); real-world prescriber preference is split with IZERVAY favoured for monthly dosing (vs. Syfovre bimonthly option) in patients with high GA growth rates. Payer coverage reached 68% of commercially insured patients in Q2 FY25, ahead of plan. IZERVAY addressable market estimated at ¥300–400B globally over 5 years as GA detection rates improve. FY26 IZERVAY guidance: ¥65–¥72B (+25–38%).',
      confidenceScore: 0.87,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Accelerate optometrist/ophthalmologist education on IZERVAY vs. Syfovre clinical differentiation — GA is primarily diagnosed by general ophthalmologists',
        'Commission real-world GA progression data studies at IZERVAY-treating centres — RWE supporting monthly dosing protocol will be valuable for payer coverage expansion',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Strategic Brands Revenue', impact: 'IZERVAY ¥52.1B; 11% of Strategic Brands FY25', trend: 'positive' },
        { driver: 'Payer Coverage Rate', impact: '68% commercial coverage at Q2 FY25; on track for 75% FY26', trend: 'positive' },
      ]),
    },
    {
      title: 'VYLOY FY25 ¥59.7B — Gastric Cancer Launch Year; Japan Domestic + China NRDL Driving Volume',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'Strategic Brands Revenue',
      kpiValue: '¥59.7B VYLOY FY25 (launch year); Japan + China primary markets',
      trendDirection: 'up',
      priority: 'high',
      summary: 'VYLOY (zolbetuximab) achieved ¥59.7B in its launch year, with Japan and China as the primary markets. VYLOY targets CLDN18.2-positive HER2-negative gastric cancer — the first approved claudin 18.2-targeted therapy globally. Japan domestic launch in April 2025 was supported by rapid hospital formulary adoption at key gastric cancer centres. China NRDL listing in January 2026 drove significant Q4 FY25 demand acceleration. US FDA approval (expected Q1 FY26) will open the largest single-country gastric cancer market. VYLOY\'s first-in-class mechanism and unmet need in gastric cancer position it for ¥120–¥140B annual peak sales potential.',
      confidenceScore: 0.83,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Prioritise US FDA approval timeline communications — US approval is the largest single VYLOY catalytic event',
        'Report CLDN18.2 testing rate growth as a leading indicator — VYLOY prescriptions require biomarker testing, so testing adoption precedes prescriptions by 6–8 weeks',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Strategic Brands Revenue', impact: 'VYLOY ¥59.7B; 12% of Strategic Brands FY25', trend: 'positive' },
        { driver: 'China Revenue', impact: 'VYLOY NRDL listing drove Q4 FY25 China acceleration', trend: 'positive' },
      ]),
    },
    {
      title: 'Strategic Brands FY26 Target ¥610–¥640B — PADCEV First-Line Ramp and VYLOY US FDA Critical Catalysts',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'Strategic Brands Revenue',
      kpiValue: 'FY26 Strategic Brands target ¥610–640B (+27–33% vs. FY25 ¥480.3B)',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Management FY26 Strategic Brands guidance of ¥610–¥640B requires +27–33% growth from FY25. The key catalysts: PADCEV first-line mUC ramp (¥265–¥285B target, +20–29% from ¥221.2B), VEOZAH payer coverage expansion to 70%+ (¥110–¥120B target), VYLOY US FDA approval and US launch (¥80–¥90B from current primarily Japan/China base), and IZERVAY continued growth (¥65–¥72B). Risk scenarios: PADCEV competition from AstraZeneca\'s EV competitive development; VYLOY US approval delay (PDUFA date under review); VEOZAH DTC advertising ROI. The 27–33% target is achievable but requires all four products delivering above mid-single-digit growth.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Communicate the key binary events for FY26 Strategic Brands guidance achievement: VYLOY US approval, VEOZAH Tier 2 payer coverage milestone, PADCEV EU first-line reimbursement',
        'Provide downside sensitivity: if VYLOY US approval delayed to FY27, Strategic Brands likely delivers ¥580–¥600B range',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Strategic Brands Revenue', impact: 'FY26 target ¥610–640B; PADCEV and VYLOY US are critical catalysts', trend: 'positive' },
        { driver: 'PADCEV Revenue', impact: 'FY26 guidance ¥265–285B; first-line mUC ramp primary driver', trend: 'positive' },
      ]),
    },
    {
      title: 'PADCEV Phase 3 EV-302 ESMO Data — OS Benefit Confirmed; Standard of Care in First-Line mUC',
      category: 'R&D Pipeline',
      insightLevel: 'L1',
      metricId: 'PADCEV Revenue',
      kpiValue: 'EV-302 Phase 3 OS HR 0.55 vs. chemotherapy; confirms first-line mUC standard of care',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Updated EV-302 Phase 3 data presented at ESMO October 2025 confirmed PADCEV (enfortumab vedotin + pembrolizumab) as the standard of care for first-line locally advanced/metastatic urothelial carcinoma (la/mUC). Overall survival hazard ratio of 0.55 vs. platinum-based chemotherapy was not yet at mature median at data cutoff — indicating durable OS benefit. The data drove an immediate sell-side consensus upward revision of PADCEV FY26 estimates by ¥40–¥50B. Key academic oncology centres (MSKCC, MD Anderson, Johns Hopkins) adopted the first-line protocol within 60 days of CMS coverage determination.',
      confidenceScore: 0.96,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'File the EV-302 sNDA data for additional label language strengthening — OS data from mature read-out should update the prescribing information',
        'Present EV-302 vs. NMIBC data comparison to clarify PADCEV positioning across bladder cancer disease states',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'PADCEV Revenue', impact: 'EV-302 data supports ¥265–285B FY26 guidance', trend: 'positive' },
        { driver: 'R&D Pipeline Value', impact: 'Phase 3 OS confirmation adds NPV certainty', trend: 'positive' },
      ]),
    },
    {
      title: 'VEOZAH Payer Coverage Milestone — 62% Commercial Coverage; 70% Target by Q3 FY26',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'VEOZAH Revenue',
      kpiValue: '62% US commercial payer coverage for VEOZAH at Q4 FY25; 70% target by Q3 FY26',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'VEOZAH commercial insurance coverage reached 62% of US commercial plan lives at Q4 FY25 — a critical prescriber inflection threshold where physician willingness to prescribe increases sharply (confirmed by market research). The key outstanding coverage gaps: United States large self-insured employers (~12% of commercial lives, primarily those awaiting the 2026 formulary cycle for VEOZAH consideration) and CVS Caremark PBM (formulary placement negotiation ongoing). The 70% target by Q3 FY26 requires these remaining large coverage agreements. VEOZAH Q1 FY26 prescription volume grew 28% above plan, supported by the 62% coverage base and DTC investment.',
      confidenceScore: 0.90,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Report payer coverage progress as a quarterly leading indicator — the 62% to 70% journey is directly measurable and investor-tracked',
        'Prioritise national PBM formulary placement negotiations; national PBM coverage impacts ~180M lives',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'VEOZAH Revenue', impact: 'Coverage at 62%; each 5pp increase drives ~¥5B additional annualised revenue', trend: 'positive' },
        { driver: 'Payer Coverage Rate', impact: 'Coverage is the primary VEOZAH growth lever FY26', trend: 'positive' },
      ]),
    },
    {
      title: 'Strategic Brands Mix Shift — Diversification from XTANDI Reducing Concentration Risk',
      category: 'Strategic Initiatives',
      insightLevel: 'L1',
      metricId: 'Strategic Brands Revenue',
      kpiValue: 'XTANDI declining from 46% to 45% of revenue as Strategic Brands grows from 18% to 22%',
      trendDirection: 'up',
      priority: 'high',
      summary: 'The portfolio diversification thesis is tracking: XTANDI\'s share of total revenue declined from 46% (FY24) to 45% (FY25) while Strategic Brands grew from 18% to 22%. By FY27, management targets Strategic Brands at 28–30% of total revenue, reducing XTANDI dependency below 40%. The diversification is both absolute (Strategic Brands ¥480B FY25 → ¥610–640B FY26) and relative (higher quality revenue from multiple products vs. single-product concentration). Investors who previously applied an XTANDI-IRA discount to Astellas equity have begun to recognise the portfolio optionality value — a narrative that should be reinforced in all investor communications.',
      confidenceScore: 0.91,
      consoleLink: '/business-consoles/strategic-brands-growth',
      recommendations: [
        'Show the portfolio mix trajectory chart in every investor presentation: FY21 XTANDI 55% → FY24 46% → FY25 45% → FY27 target <40%',
        'Frame Strategic Brands as additive, not just substitutive — total revenue growing while diversifying is a superior narrative',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Strategic Brands Revenue', impact: 'Portfolio mix shift from XTANDI reduces concentration risk', trend: 'positive' },
        { driver: 'XTANDI Revenue', impact: 'Share declining as Strategic Brands grows — managed transition', trend: 'neutral' },
      ]),
    },

    // =========================================================================
    // SMT COST TRANSFORMATION (5 insights)
    // =========================================================================
    {
      title: 'SMT FY25 ¥21B Delivered — ¥3B Above ¥18B Initial Target; Phase 1 Complete 6 Months Early',
      category: 'Strategic Initiatives',
      insightLevel: 'L1',
      metricId: 'SMT Savings',
      kpiValue: '¥21B FY25 SMT savings vs ¥18B initial target (+16.7%); Phase 1 complete October 2025',
      trendDirection: 'up',
      priority: 'high',
      summary: 'The Sustainable Margin Transformation (SMT) programme delivered ¥21B in verified savings in FY25 — ¥3B above the ¥18B initial target. Phase 1 (organisational redesign, procurement renegotiation, manufacturing rationalisation) was declared complete in October 2025 — 6 months ahead of the April 2026 plan. Procurement savings outperformed by ¥1.8B; headcount reductions achieved 12% more cost reduction than planned. The early Phase 1 completion enabled Phase 2 (IT rationalisation, shared services expansion) to begin 6 months earlier, pulling forward ¥5–¥8B of FY26 savings delivery.',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Disclose SMT savings by programme phase quarterly: Phase 1 complete (¥21B), Phase 2 in-progress (FY26–27), Phase 3 planned (FY27–28)',
        'Show the XTANDI IRA offset calibration: ¥40B FY26 SMT provides 4x coverage of ¥9.6B IRA base impact',
        'Consider increasing the ¥65B cumulative target — the Phase 1 overperformance suggests additional headroom in Phase 2',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: '¥21B FY25 delivered; ¥40B FY26 target on track', trend: 'positive' },
        { driver: 'Core OP Margin', impact: 'SMT primary driver of margin expansion toward 27-28%', trend: 'positive' },
      ]),
    },
    {
      title: 'SMT SG&A Ratio — 40.2% FY25 → Sub-39% FY26 Target; Structural Reduction Programme',
      category: 'Strategic Initiatives',
      insightLevel: 'L2',
      metricId: 'SMT Savings',
      kpiValue: 'SG&A 40.2% of Core Revenue FY25; Phase 2 targets sub-39% by FY26 Q4',
      trendDirection: 'down',
      priority: 'high',
      summary: 'SG&A as a percentage of Core Revenue was 40.2% in FY25 — down from 43.1% in FY24, an improvement of 290bps driven by the SMT Phase 1 headcount reductions and structural overhead elimination. The FY26 target of sub-39% requires an additional 120bps reduction, to be delivered through Phase 2 IT rationalisation (ERP consolidation, CRM platform integration) and shared services centre expansion in lower-cost geographies. Best-in-class global pharma SG&A benchmarks for comparable-size companies (AstraZeneca ~36%, Novartis ~38%) suggest further structural improvement potential beyond FY26.',
      confidenceScore: 0.89,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Disclose SG&A by category: Sales & Marketing, G&A, Distribution — G&A is the primary SMT Phase 2 lever, while Sales & Marketing should be protected for launch brands',
        'Benchmark SG&A ratio vs. pharma peers in quarterly reports to demonstrate progress toward best-in-class targets',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: 'SG&A from 43.1% to 40.2%; sub-39% FY26 target', trend: 'positive' },
        { driver: 'Core OP Margin', impact: 'SG&A improvement directly expands Core OP margin', trend: 'positive' },
      ]),
    },
    {
      title: 'SMT Manufacturing Rationalisation — API Dual-Sourcing 85%; CMO Rate Renegotiations Saving ¥4.5B',
      category: 'Strategic Initiatives',
      insightLevel: 'L2',
      metricId: 'SMT Savings',
      kpiValue: 'API dual-sourcing 85% portfolio coverage; CMO renegotiations ¥4.5B savings vs ¥3.0B target',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'Manufacturing SMT programme delivered ¥4.5B in savings vs. the ¥3.0B target, driven by CMO (contract manufacturing organisation) rate renegotiations that leveraged Astellas\'s consolidated volume commitments. API dual-sourcing has been extended to 85% of portfolio by value, reducing supply concentration risk for XTANDI and PADCEV API (critical supply chains). Batch success rate reached 98.5% (above the 98% target) as advanced analytics were applied to process parameter monitoring. The ¥4.5B manufacturing savings represent 21% of the total ¥21B FY25 SMT delivery — manufacturing is a proportionally larger contributor than originally planned.',
      confidenceScore: 0.87,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Extend CMO renegotiations to Phase 2 target of 100% API dual-sourcing by end FY26 — remaining 15% represents higher supply risk',
        'Report supply reliability (batch OTD rate) as an operational KPI alongside the financial savings — PADCEV cold chain 99.6% OTD is a competitive advantage',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: 'Manufacturing ¥4.5B vs ¥3.0B target; Phase 2 savings pulled forward', trend: 'positive' },
        { driver: 'Core OP Margin', impact: 'Manufacturing efficiency directly improves COGS ratio', trend: 'positive' },
      ]),
    },
    {
      title: 'SMT Phase 2 Roadmap — IT Rationalisation and Shared Services: ¥15–18B FY26 Target',
      category: 'Strategic Initiatives',
      insightLevel: 'L2',
      metricId: 'SMT Savings',
      kpiValue: 'SMT Phase 2 FY26 target ¥15–18B; total ¥40B FY26 requires Phase 2 delivery',
      trendDirection: 'up',
      priority: 'high',
      summary: 'SMT Phase 2, launched 6 months ahead of schedule in October 2025, targets ¥15–¥18B of additional savings in FY26 from IT systems rationalisation and shared services centre expansion. Key Phase 2 workstreams: (1) ERP consolidation from 5 legacy systems to 2 SAP S/4HANA instances (¥5–¥7B savings); (2) CRM and customer engagement platform integration (¥2–¥3B); (3) Finance and HR shared services centre build-out in Osaka and Manila (¥4–¥5B); (4) R&D IT platform optimisation (¥3–¥4B). Phase 2 one-time costs of ¥8–¥10B are expected in FY26, excluded from Core financials. Completion target: Q2 FY27.',
      confidenceScore: 0.82,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Provide quarterly Phase 2 milestones in earnings materials to maintain investor confidence in the ¥40B FY26 total target',
        'Disclose one-time Phase 2 restructuring charges separately from Core earnings to prevent confusion',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: 'Phase 2 ¥15–18B required to hit ¥40B FY26 total target', trend: 'positive' },
        { driver: 'Core OP Margin', impact: 'IT and shared services savings expand margin toward 28%', trend: 'positive' },
      ]),
    },
    {
      title: 'SMT Cumulative Target ¥65B — On Track Through FY28; Structural Margin Improvement Secured',
      category: 'Strategic Initiatives',
      insightLevel: 'L1',
      metricId: 'SMT Savings',
      kpiValue: '¥65B cumulative SMT target through FY28; ¥21B FY25 + ¥40B FY26 = ¥61B run-rate',
      trendDirection: 'up',
      priority: 'high',
      summary: 'The ¥65B cumulative SMT savings target through FY28 is on track with ¥21B FY25 delivery and ¥40B FY26 target — representing ¥61B of cumulative annualised run-rate. The FY27–FY28 Phase 3 programme (digital transformation, AI-enabled process automation, supply chain AI) is expected to deliver the remaining ¥4–¥15B of incremental savings. The structural nature of SMT savings (systematic process redesign, not one-time actions) means savings are additive to each year\'s base — a ¥65B cumulative programme represents approximately 310bps of Core OP margin improvement at current revenue levels.',
      confidenceScore: 0.86,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Disclose the cumulative savings waterfall chart annually — ¥21B + ¥40B + Phase 3 target toward ¥65B+ cumulative',
        'Communicate that SMT savings are structural (recurring) not one-time — the annualised run-rate improvement is durable',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'SMT Savings', impact: '¥65B cumulative target; ¥61B run-rate after FY25+FY26', trend: 'positive' },
        { driver: 'Core OP Margin', impact: '¥65B cumulative = ~310bps structural margin improvement', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // FX EXPOSURE (4 insights)
    // =========================================================================
    {
      title: 'FX Sensitivity ¥2.1B Core OP per ¥1 USD/JPY — 56% Non-Japan Revenue Creates Material Exposure',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'USD/JPY Rate',
      kpiValue: '¥2.1B Core OP per ¥1 USD/JPY move; ¥151/USD FY25 baseline; 56% non-Japan revenue',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'With 56% of Astellas revenue generated outside Japan, USD/JPY is the primary FX sensitivity driver (USD approximately 35–38% of revenue). Each ¥1 move in USD/JPY drives approximately ¥2.1B in Core OP. At the FY25 average rate of ¥149.8 vs. the ¥151 planning assumption, FX was a net headwind of approximately -¥2.5B to Core OP. Hedging coverage of 30–33% of anticipated USD cash flows reduces but does not eliminate FX sensitivity to approximately ¥1.45B Core OP per ¥1 move on a net-of-hedges basis. EUR/JPY and CNY/JPY provide secondary sensitivities (¥0.8B and ¥0.3B per 5% move respectively).',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Disclose quarterly FX sensitivity table: USD/JPY, EUR/JPY, CNY/JPY sensitivities under ±5% and ±10% rate scenarios',
        'Consider increasing hedge coverage ratio from 33% to 40–45% for FY26 given elevated USD/JPY uncertainty',
        'Report hedge book position (notional, duration, strike) annually — investors model FX impact and need the hedging parameters',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'USD/JPY Rate', impact: '¥2.1B Core OP per ¥1 move; ¥151 FY25 baseline', trend: 'neutral' },
        { driver: 'Core OP', impact: '56% non-Japan revenue; FX is largest uncontrolled earnings variable', trend: 'negative' },
      ]),
    },
    {
      title: 'USD/JPY FY25 Average ¥149.8 — Headwind vs ¥151 Plan; Q3 JPY Strength Main Driver',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'USD/JPY Rate',
      kpiValue: 'FY25 USD/JPY avg ¥149.8 vs ¥151 plan; approximately -¥2.5B Core OP headwind',
      trendDirection: 'down',
      priority: 'medium',
      summary: 'FY25 average USD/JPY of ¥149.8 was ¥1.2 unfavourable vs. the ¥151 planning assumption, primarily due to Q3 FY25 JPY appreciation (USD/JPY declined to ¥147–¥149 range in October–November 2025 as BOJ policy rate expectations shifted). The full-year FX headwind was approximately -¥2.5B to Core OP (¥1.2 × ¥2.1B sensitivity). FX hedging reduced the realised headwind to approximately -¥1.7B. FY26 planning assumption remains ¥151; Q1 FY26 actual was ¥153 (+¥1.2B Core OP tailwind vs. plan, supporting the Q1 FY26 EPS beat).',
      confidenceScore: 0.93,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Provide quarterly FX actual vs. plan variance disclosure in earnings materials to maintain modelling transparency',
        'If BOJ raises rates further in FY26, JPY appreciation risk materialises — update FX scenario disclosures to include 140 and 145 stress cases',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'USD/JPY Rate', impact: 'FY25 avg ¥149.8 vs ¥151 plan; -¥2.5B Core OP headwind', trend: 'negative' },
        { driver: 'Core OP', impact: 'Net-of-hedges headwind -¥1.7B FY25', trend: 'negative' },
      ]),
    },
    {
      title: 'Hedging Programme — 30-33% USD Coverage; Partial Protection Against JPY Strength Scenarios',
      category: 'Risk & Compliance',
      insightLevel: 'L2',
      metricId: 'USD/JPY Rate',
      kpiValue: '30-33% USD cash flow hedging; 12-18 month forward coverage at ¥148–¥152 strikes',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Astellas hedges 30–33% of anticipated USD operating cash inflows using forward contracts and options with 12–18 month duration. The hedge book provides partial protection against JPY appreciation while preserving upside participation in USD strengthening scenarios. FY25 hedges were primarily in the ¥148–¥152 strike range, providing approximately 50% of the maximum loss scenario (JPY appreciates to ¥140) while allowing full benefit in the favourable scenario (JPY depreciates to ¥155+). Management has indicated willingness to extend hedge coverage to 40–45% if BOJ policy normalisation creates higher JPY appreciation risk.',
      confidenceScore: 0.85,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Consider moving hedge coverage to 40-45% as the BOJ normalisation path becomes clearer in FY26',
        'Disclose hedge book structure (notional value, weighted average strike, duration) to enable more precise investor FX modelling',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'USD/JPY Rate', impact: 'Hedge book reduces net sensitivity from ¥2.1B to ¥1.45B per ¥1', trend: 'neutral' },
        { driver: 'Core OP', impact: 'Hedging programme limits downside in JPY appreciation scenarios', trend: 'positive' },
      ]),
    },
    {
      title: 'Multi-Currency FX Exposure — EUR/JPY and CNY/JPY Secondary Sensitivities',
      category: 'Financial Performance',
      insightLevel: 'L2',
      metricId: 'USD/JPY Rate',
      kpiValue: 'EUR/JPY ¥0.8B / 5% move; CNY/JPY ¥0.3B / 5% move; secondary to USD/JPY',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Beyond USD/JPY, Astellas has secondary FX exposures: EUR/JPY (Established Markets revenue approximately 18% of total, sensitivity ¥0.8B Core OP per 5% move), CNY/JPY (China 5% of revenue, sensitivity ¥0.3B per 5% move), and GBP/JPY (UK as part of Established Markets, secondary sensitivity). As China revenue grows toward ¥150B in FY26 (7% of total), CNY/JPY sensitivity will increase. China revenue is partially denominated in RMB with transfer pricing arrangements to JPY group reporting. EUR/JPY was broadly stable in FY25 (FY25 avg EUR/JPY ¥162 vs ¥163 plan), a minor headwind.',
      confidenceScore: 0.82,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Expand FX sensitivity disclosures to include EUR/JPY and CNY/JPY as China grows to 7%+ of revenue',
        'Consider EUR-denominated hedging as European PADCEV/VEOZAH revenues scale',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Established Markets Revenue', impact: 'EUR/JPY secondary FX sensitivity ¥0.8B per 5%', trend: 'neutral' },
        { driver: 'China Revenue', impact: 'CNY/JPY sensitivity growing as China reaches 7% of revenue', trend: 'neutral' },
      ]),
    },

    // =========================================================================
    // JAPAN NHI AND GEOGRAPHIC SEGMENTS (4 insights)
    // =========================================================================
    {
      title: 'Japan NHI Revision April 2025 — -6.2% Average Price Cut; Favourable End of -5% to -8% Range',
      category: 'Risk & Compliance',
      insightLevel: 'L1',
      metricId: 'Japan Revenue',
      kpiValue: '-6.2% Japan NHI price revision April 2025; -¥7.8B impact vs. -¥10.2B worst case',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'The April 2025 Japan NHI biennial price revision resulted in a -6.2% average price reduction on Astellas\'s Japan pharmaceutical portfolio — at the favourable end of the -5% to -8% guidance range. XTANDI benefited from a value-based price maintenance clause (higher innovation score offsetting the standard cut); VYLOY received a launch price exempt from the revision cycle. Japan revenue impact: approximately -¥7.8B FY25 vs. a -¥10.2B worst-case scenario — a ¥2.4B favourable variance. The next Japan NHI revision is scheduled for April 2027. Japan NHI is a predictable, biennial risk with known timing and magnitude range.',
      confidenceScore: 0.96,
      consoleLink: '/business-consoles/international-asia-performance',
      recommendations: [
        'Develop formal Japan NHI modelling framework: publish base (-6%), adverse (-8%), and upside (-4%) scenarios for the April 2027 revision 18 months in advance',
        'Track VYLOY Japan hospital formulary listings as the near-term Japan revenue growth catalyst to offset NHI base erosion',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Japan Revenue', impact: '-6.2% NHI revision; -¥7.8B impact FY25', trend: 'negative' },
        { driver: 'Core OP Margin', impact: 'NHI Q4 accrual creates Q4 margin trough seasonality', trend: 'neutral' },
      ]),
    },
    {
      title: 'China Revenue FY25 ¥101.5B — +29.6% YoY; VYLOY NRDL Listing Catalysing Next Growth Phase',
      category: 'Revenue & Market',
      insightLevel: 'L1',
      metricId: 'China Revenue',
      kpiValue: '¥101.5B FY25 China Revenue (+29.6% YoY); VYLOY NRDL Jan 2026; FY26 target ¥140–150B',
      trendDirection: 'up',
      priority: 'high',
      summary: 'China revenue grew +29.6% to ¥101.5B in FY25, establishing China as Astellas\'s fastest-growing geographic segment. The Q4 FY25 acceleration (above 20% full-year plan) was driven by the VYLOY NRDL listing effective January 2026, which created channel buy-in demand in Q4. PADCEV received NMPA approval for urothelial carcinoma in December 2025, adding a second growth driver in China for FY26. FY26 management guidance of ¥140–¥150B (+38–+48%) requires the VYLOY NRDL patient volume ramp (typical 3–5x volume uplift within 18 months) and PADCEV launch year contribution.',
      confidenceScore: 0.89,
      consoleLink: '/business-consoles/international-asia-performance',
      recommendations: [
        'Report China revenue quarterly separately from the International Markets segment — China\'s growth rate and growth drivers are distinct from LATAM/APAC/EM',
        'Monitor VYLOY NRDL prescription volume monthly — NRDL ramp typically hits inflection at months 3–6 post-listing',
        'PADCEV China launch (NMPA approval December 2025) is the second-largest China revenue opportunity after VYLOY',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'China Revenue', impact: '¥101.5B +29.6% FY25; FY26 target ¥140–150B', trend: 'positive' },
        { driver: 'VYLOY Revenue', impact: 'NRDL listing January 2026 drives Q4 FY25 + FY26 ramp', trend: 'positive' },
      ]),
    },
    {
      title: 'Established Markets ¥563.6B FY25 — Stable Growth; PADCEV European Launch Offsetting Mature Product Erosion',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'Established Markets Revenue',
      kpiValue: '¥563.6B FY25 Established Markets; PADCEV European reimbursements received Q1 FY25',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Established Markets segment (Western Europe, Canada, Australia, select regulated markets) revenue of ¥563.6B was broadly stable in FY25, with PADCEV and VEOZAH European launches (+28% and initial launch YoY) offsetting mature product generic erosion and NHI-equivalent pricing pressures in France and Germany. European PADCEV reimbursement decisions in Germany, UK, France, and Spain were all received in Q1 FY25. VEOZAH received EMA approval in Q4 FY24 and launched commercially in Germany, UK, and Sweden in Q1 FY25. European growth is expected to accelerate in FY26 as full-year contributions from both products take effect.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/international-asia-performance',
      recommendations: [
        'Track PADCEV European HTA decisions quarterly — Germany, France, Italy, Spain, UK all have distinct HTA processes with significant reimbursement impact',
        'VEOZAH European launch is contingent on NICE guidance in UK and early G-BA negotiations in Germany — monitor closely',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Established Markets Revenue', impact: '¥563.6B; PADCEV Europe offsetting mature erosion', trend: 'neutral' },
        { driver: 'PADCEV Revenue', impact: 'European reimbursements received Q1 FY25; FY26 full-year contribution', trend: 'positive' },
      ]),
    },
    {
      title: 'Japan Revenue ¥289.0B FY25 — NHI Headwind Managed; VYLOY Domestic Launch Driving Next Phase',
      category: 'Revenue & Market',
      insightLevel: 'L2',
      metricId: 'Japan Revenue',
      kpiValue: '¥289.0B FY25 Japan Revenue; XTANDI domestic stable; VYLOY April 2025 launch',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Japan segment revenue of ¥289.0B in FY25 absorbed the -6.2% NHI price revision impact (approximately -¥7.8B) while growing slightly in volume terms, primarily from XTANDI stable market position and VYLOY domestic launch (April 2025). XTANDI Japan market share in prostate cancer remains >70% — Astellas\'s home market advantage combined with the longest-tenured product in the indication creates durable volume. VYLOY\'s first-in-class CLDN18.2-targeted gastric cancer mechanism addresses an unmet need in Japan\'s high-incidence gastric cancer market. FY26 Japan revenue target: ¥295–¥310B (+2–7%), with VYLOY ramp offsetting NHI base erosion.',
      confidenceScore: 0.90,
      consoleLink: '/business-consoles/international-asia-performance',
      recommendations: [
        'Report Japan revenue decomposition: XTANDI (stable), VYLOY (growing), mature products (declining) — this shows the underlying growth story',
        'VYLOY Japan hospital formulary access expansion by oncology tier (Tier 1/2/3 cancer hospitals) is the key volume driver to track monthly',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Japan Revenue', impact: '¥289.0B FY25; NHI managed; VYLOY launch driver', trend: 'neutral' },
        { driver: 'VYLOY Revenue', impact: 'Japan launch April 2025; hospital formulary ramp ongoing', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // R&D PIPELINE AND CAPITAL ALLOCATION (6 insights)
    // =========================================================================
    {
      title: 'R&D Pipeline — 3 Phase 3 POC Successes FY25; Pipeline NPV Optionality Undervalued by Market',
      category: 'R&D Pipeline',
      insightLevel: 'L1',
      metricId: 'R&D Pipeline Value',
      kpiValue: '3 Phase 3 POC successes FY25; ~¥800B pipeline NPV potential at risk-adjusted peak sales',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Astellas achieved 3 Phase 3 proof-of-concept milestones in FY25 (ASP3550/FGFR inhibitor mUC, selumetinib collaboration, ASP7927 oncology), validating the pipeline productivity of the focused oncology/urology strategy. Each Phase 3 POC in Astellas\'s model is associated with approximately ¥150–¥300B in potential peak sales NPV if the molecule achieves approval and launch. R&D efficiency (14.6% R&D/revenue) positions Astellas in the top quartile of mid-large pharma. FY26 pipeline milestones include 3 additional Phase 3 initiations and continued XTANDI combination study data.',
      confidenceScore: 0.83,
      consoleLink: '/business-consoles/enterprise-pipeline',
      recommendations: [
        'Publish a comprehensive pipeline NPV disclosure in the Annual Report — quantifying the risk-adjusted value creation from the R&D programme helps investors go beyond the marketed product franchise',
        'Highlight the Phase 3 POC success rate (3 of 3 = 100% in FY25) as evidence of disciplined portfolio selection — this rate is above industry average',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'R&D Pipeline Value', impact: '3 POC successes FY25; ~¥800B risk-adjusted NPV potential', trend: 'positive' },
        { driver: 'R&D Expense', impact: '14.6% R&D intensity; top-quartile efficiency', trend: 'positive' },
      ]),
    },
    {
      title: 'R&D Efficiency 14.6% — Top-Quartile vs. Pharma Peers; Adaptive Trial Design Driving Productivity',
      category: 'R&D Pipeline',
      insightLevel: 'L2',
      metricId: 'R&D Expense',
      kpiValue: 'R&D 14.6% of Core Revenue FY25 vs. 18-22% pharma peer average',
      trendDirection: 'down',
      priority: 'medium',
      summary: 'Astellas Core R&D expense of 14.6% of Core Revenue is 360–750bps better than the 18–22% range typical among comparable pharma peers (AstraZeneca ~19%, Novartis ~18%, Pfizer ~22%). The efficiency reflects SMT programme optimisations in R&D (CRO procurement, digital trial platforms, adaptive design adoption), portfolio discipline (4 early-stage programmes terminated FY25), and collaboration revenue offset. R&D absolute spend of ¥312.4B (FY25) supports the 3 Phase 3 POC pipeline, multiple Phase 2 studies, and the XTANDI combination study programme.',
      confidenceScore: 0.90,
      consoleLink: '/business-consoles/enterprise-pipeline',
      recommendations: [
        'Disclose R&D productivity metrics: Phase 3 POC successes per ¥100B invested, vs. pharma peers — Astellas appears to be above-average productivity',
        'Consider increasing R&D investment ratio back toward 16% as pipeline advances toward Phase 3 initiations — maintaining pipeline depth is critical for FY27+ revenue',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'R&D Expense', impact: '14.6% of revenue vs. 18-22% peers; top-quartile efficiency', trend: 'positive' },
        { driver: 'Core OP Margin', impact: 'Lower R&D ratio is a margin improvement contributor', trend: 'positive' },
      ]),
    },
    {
      title: 'Capital Allocation — Dividend ¥78/Share FY25 + ¥50B Buyback; Net Cash +¥82B Enables Returns',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Operating Cash Flow',
      kpiValue: '¥78/share FY25 dividend (¥139.7B total); ¥50B share buyback; net cash +¥82B',
      trendDirection: 'up',
      priority: 'high',
      summary: 'Astellas\'s capital allocation framework prioritised shareholder returns in FY25 given the strong FCF generation (¥520.8B) and net cash position (+¥82B). The ¥78/share full-year dividend (¥139.7B total payout) represents a 33% payout ratio vs. Core Net Income — conservative relative to global pharma peers but sustainable through the IRA uncertainty period. A ¥50B share buyback programme announced in March 2026 signals management confidence in the FY26+ earnings trajectory. Capital allocation priority order: dividend maintenance → buyback → bolt-on M&A (platforms or late-stage assets complementary to oncology/urology pipeline).',
      confidenceScore: 0.93,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Communicate multi-year dividend growth trajectory: FY26 target ¥85–¥90/share (+9–15%) is achievable at ¥248–¥255 Core EPS',
        'Provide buyback completion timeline and anti-dilution intent — the ¥50B programme has strategic signalling value',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Operating Cash Flow', impact: 'FCF ¥520.8B enables ¥139.7B dividend + ¥50B buyback', trend: 'positive' },
        { driver: 'Core EPS', impact: 'Buyback reduces share count, accretive to EPS growth trajectory', trend: 'positive' },
      ]),
    },
    {
      title: 'Pipeline FY26 Initiations — 3 Phase 3 Starts Planned; XTANDI Combination and ADC Programme',
      category: 'R&D Pipeline',
      insightLevel: 'L2',
      metricId: 'R&D Pipeline Value',
      kpiValue: '3 Phase 3 initiations planned FY26; XTANDI combo, ADC programme, selective androgen receptor modulator',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'FY26 R&D plan includes initiating 3 new Phase 3 studies: (1) XTANDI + novel AR-targeted agent combination in early-line CRPC (aims to extend patent value and delay ARSi class competitive obsolescence); (2) antibody-drug conjugate (ADC) programme in HER2-low breast cancer (leveraging PADCEV ADC manufacturing expertise); and (3) a selective androgen receptor modulator (SARM) for muscle wasting/sarcopenia (first-in-class mechanism, non-oncology indication). Each initiation represents approximately ¥15–25B in incremental Phase 3 investment over 4–6 years. The ADC programme leverages the manufacturing platform established for PADCEV.',
      confidenceScore: 0.78,
      consoleLink: '/business-consoles/enterprise-pipeline',
      recommendations: [
        'Communicate the XTANDI combination study as an IRA mitigation strategy — if the combination demonstrates OS benefit in pre-IRA CRPC, it resets the clinical standard and potentially extends the treatment franchise',
        'ADC platform investment in non-PADCEV indications demonstrates R&D diversification beyond prostate/bladder cancer',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'R&D Pipeline Value', impact: '3 Phase 3 initiations FY26 expanding pipeline depth', trend: 'positive' },
        { driver: 'R&D Expense', impact: 'Phase 3 initiations add ¥15-25B per study to R&D spend', trend: 'neutral' },
      ]),
    },
    {
      title: 'ALPMY TSR FY25 +18.4% — Outperformed MSCI Pharma Index +8.2% by 1,020bps',
      category: 'Financial Performance',
      insightLevel: 'L1',
      metricId: 'Core EPS',
      kpiValue: 'ALPMY ADR TSR +18.4% FY25 vs MSCI Pharma Index +8.2%; 1,020bps outperformance',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'ALPMY ADR total shareholder return of +18.4% in FY25 outperformed the MSCI Pharma & Biotech Index (+8.2%) by 1,020 basis points. The outperformance was driven by: Core EPS +49.8% YoY (¥158 → ¥237), PADCEV EV-302 ESMO data re-rating in October 2025, SMT delivery ahead of plan improving cost credibility, and VEOZAH launch momentum validating the women\'s health diversification thesis. The FY24 XTANDI IRA discount has partially reversed as investors weigh the strategic portfolio diversification and SMT offset. FY26 outperformance potential depends on IRA final MFP clarity and Strategic Brands tracking to guidance.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Highlight IRA risk management credibility as the source of re-rating: the market discounted Astellas for IRA uncertainty in FY24, and the ¥9.6B disclosed sensitivity with ¥40B SMT offset is reducing that discount',
        'Maintain quarterly outperformance vs. MSCI Pharma benchmark in investor materials as evidence of strategy execution',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core EPS', impact: '+49.8% YoY primary driver of TSR re-rating', trend: 'positive' },
        { driver: 'Strategic Brands Revenue', impact: 'Portfolio diversification narrative reducing IRA discount', trend: 'positive' },
      ]),
    },
    {
      title: 'PADCEV Manufacturing — ADC Cold Chain 99.6% OTD; Scale-Up for FY26 Demand Critical',
      category: 'Operational Excellence',
      insightLevel: 'L2',
      metricId: 'PADCEV Revenue',
      kpiValue: 'PADCEV ADC cold chain 99.6% on-time delivery; Yamaguchi site expansion FY26',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'PADCEV (enfortumab vedotin) is an antibody-drug conjugate (ADC) requiring cold-chain manufacturing and distribution — a technically complex supply chain with higher risk vs. conventional oral oncology agents. ADC on-time delivery has been maintained at 99.6% through FY25 despite a 34.8% volume increase, reflecting successful manufacturing scale-up at the Yamaguchi GMP facility (Phase 1 expansion completed Q2 FY25). The Phase 2 Yamaguchi expansion (FY26–FY27, ¥9.1B capital investment) will increase PADCEV API capacity by approximately 60%, supporting the FY26 ¥265–285B guidance and preventing supply constraints in the first-line mUC launch ramp.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/smt-cost-transformation',
      recommendations: [
        'Report PADCEV manufacturing capacity vs. demand trajectory quarterly — supply constraint is the primary operational risk to first-line mUC ramp realisation',
        'Disclose Yamaguchi Phase 2 expansion milestones to demonstrate supply planning discipline',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'PADCEV Revenue', impact: 'Supply capacity must match +20-29% FY26 revenue growth', trend: 'positive' },
        { driver: 'SMT Savings', impact: 'Manufacturing efficiency balances investment with cost reduction', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // COMPETITIVE INTELLIGENCE (4 insights)
    // =========================================================================
    {
      title: 'Global Oncology Market ¥285T — Astellas 3.1% Share; PADCEV and Pipeline Expanding Market Position',
      category: 'Competitive Intelligence',
      insightLevel: 'L1',
      metricId: 'Total Revenue',
      kpiValue: 'Global oncology market ~¥285T; Astellas 3.1% share; targeting 4%+ by FY28',
      trendDirection: 'up',
      priority: 'high',
      summary: 'The global oncology pharmaceutical market is approximately ¥285 trillion ($1.9 trillion equivalent), growing at 12–15% CAGR. Astellas\'s oncology revenue (XTANDI + PADCEV + VYLOY) represents approximately 3.1% global market share — up from 2.8% in FY24. The management target is 4%+ share by FY28 as PADCEV first-line mUC and VYLOY gastric cancer markets develop. Key share drivers: PADCEV\'s ADC leadership in urothelial carcinoma and the unique VYLOY mechanism in gastric cancer (both significant unmet needs). Competitive threats: AstraZeneca/Daiichi oncology ADC platform, J&J prostate cancer franchise, Merck immunotherapy expansion.',
      confidenceScore: 0.82,
      consoleLink: '/business-consoles/americas-performance',
      recommendations: [
        'Quantify oncology market share in annual report and investor presentations — the 2.8% to 3.1% trajectory demonstrates compounding market position',
        'Map PADCEV\'s mUC market opportunity with patient funnel data: diagnosed → tested → eligible → treated — this gives investors a more precise TAM understanding',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Total Revenue', impact: 'Oncology market share 3.1%; targeting 4%+ by FY28', trend: 'positive' },
        { driver: 'PADCEV Revenue', impact: 'ADC leadership in mUC is the primary share gain mechanism', trend: 'positive' },
      ]),
    },
    {
      title: 'AstraZeneca Competition — LYNPARZA PARP Inhibitor in BRCA+ Prostate; Datopotamab DXd ADC Watch',
      category: 'Competitive Intelligence',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'AstraZeneca/Merck LYNPARZA 18% prostate cancer share in BRCA+ sub-population; Dato-DXd ADC development',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'AstraZeneca and Merck\'s LYNPARZA (olaparib) competes with XTANDI in BRCA1/2-mutated prostate cancer patients — a genomically defined sub-population representing approximately 10–15% of mCRPC patients. LYNPARZA holds approximately 18% share in this sub-population. XTANDI\'s advantage is non-genomically-selected prescribing (broader label), while LYNPARZA combination with abiraterone has some evidence. AstraZeneca\'s datopotamab deruxtecan (Dato-DXd) ADC programme in urothelial carcinoma, if successful, would compete with PADCEV — currently in Phase 2; clinical read-out expected FY26–FY27.',
      confidenceScore: 0.80,
      consoleLink: '/business-consoles/americas-performance',
      recommendations: [
        'Monitor Dato-DXd Phase 2 data closely — if the ADC shows strong activity in mUC, competitive intelligence should quantify the share risk to PADCEV in a scenario analysis',
        'XTANDI BRCA+ combination studies with PARP inhibitors should be tracked for label-broadening potential',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: 'AstraZeneca competition in BRCA+ sub-population 10-15% of mCRPC', trend: 'negative' },
        { driver: 'PADCEV Revenue', impact: 'Dato-DXd ADC FY26-27 clinical read-out is watch item', trend: 'neutral' },
      ]),
    },
    {
      title: 'J&J/Pfizer ERLEADA Competition — 24% ARSi Share; Post-IRA Competitive Dynamics Evolving',
      category: 'Competitive Intelligence',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'ERLEADA 24% ARSi share vs. XTANDI 48.2%; darolutamide 14%; post-IRA prescribing shifts monitored',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'J&J\'s ERLEADA (apalutamide) holds approximately 24% ARSi market share and Bayer/Nurix\'s darolutamide approximately 14%, vs. XTANDI\'s 48.2%. ERLEADA and darolutamide are not included in the current IRA MFP negotiation cycle, creating a relative price advantage post-XTANDI MFP implementation. Astellas\'s commercial monitoring detected a modest Q1 FY26 prescribing shift to ERLEADA at 2 high-volume academic centres — the early signal is below the threshold for formal guidance revision but warrants ongoing monitoring. XTANDI\'s broader label (covering all mCRPC and mCSPC/nmCSPC/nmCRPC disease states) vs. ERLEADA (mCSPC and nmCRPC only) remains the primary clinical differentiation.',
      confidenceScore: 0.85,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Conduct weekly oncologist sentiment tracking on IRA-awareness-driven ERLEADA/darolutamide switching intention — early detection enables commercial response before market share deteriorates',
        'Deploy XTANDI real-world outcome studies vs. ERLEADA at the 20 highest-volume prescribing oncology centres as a proactive defence',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI US Market Share', impact: 'ERLEADA 24% + darolutamide 14%; post-IRA risk of further shifts', trend: 'negative' },
        { driver: 'XTANDI Revenue', impact: 'US volume watch item; international not affected by IRA', trend: 'neutral' },
      ]),
    },
    {
      title: 'Pfizer XTANDI Co-Promotion — Partnership Providing US Commercial Scale; Royalty Structure',
      category: 'Strategic Initiatives',
      insightLevel: 'L2',
      metricId: 'XTANDI Revenue',
      kpiValue: 'Astellas/Pfizer XTANDI co-promote; royalty/milestone structure drives Q3 FY25 earnings',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Pfizer co-promotes XTANDI in the US under a long-standing collaboration agreement with Astellas. The partnership provides Astellas access to Pfizer\'s US oncology sales force scale while generating royalty and milestone payments. The Q3 FY25 ¥8.5B milestone payment was associated with a US market exclusivity extension confirmation. Under IRA MFP implementation, the co-promotion economics will need renegotiation to reflect the reduced US net price baseline — the existing royalty structure references WAC-based revenue calculations that will change under MFP. Transition planning for this commercial agreement is a FY26 management priority.',
      confidenceScore: 0.81,
      consoleLink: '/business-consoles/oncology-xtandi-performance',
      recommendations: [
        'Disclose the IRA impact on co-promotion economics once negotiations with Pfizer conclude — investors need visibility into net profit sharing post-MFP',
        'Evaluate whether the co-promotion structure remains optimal as XTANDI US volume potentially declines — alternative commercial structures may provide better economics for Astellas',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'XTANDI Revenue', impact: 'Pfizer co-promote provides US sales scale; MFP renegotiation needed', trend: 'neutral' },
        { driver: 'Core OP', impact: 'Royalty structure contributes Q3 FY25 milestone ¥8.5B', trend: 'positive' },
      ]),
    },

    // =========================================================================
    // ENTERPRISE RISK AND GOVERNANCE (4 insights)
    // =========================================================================
    {
      title: 'Credit Rating — Moody\'s A3 / S&P A-; Net Cash Position +¥82B Supports Strong Balance Sheet',
      category: 'Risk & Compliance',
      insightLevel: 'L2',
      metricId: 'Operating Cash Flow',
      kpiValue: 'Moody\'s A3 / S&P A- credit rating; net cash +¥82B at FY25 year-end',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'Astellas maintains A3/A- investment-grade credit ratings reflecting the strong free cash flow profile (¥520.8B FY25), net cash position (+¥82B), and disciplined capital allocation. Net cash (not net debt) is unusual among mid-large pharma — most peers carry net debt from M&A. Astellas\'s net cash position provides balance sheet optionality for strategic M&A (bolt-on pipeline assets or technology platform acquisitions) while maintaining the capability to increase shareholder returns. Moody\'s and S&P affirmed stable outlooks following the FY25 results, noting the SMT delivery and portfolio diversification progress as positive factors.',
      confidenceScore: 0.95,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Maintain net cash disclosure as a key balance sheet strength differentiator vs. debt-levered pharma peers',
        'Quantify the M&A optionality: with ¥82B net cash + ¥520B FCF, Astellas can fund a ¥200–¥400B bolt-on acquisition without impacting credit rating',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Operating Cash Flow', impact: 'Net cash +¥82B; credit strength supports strategic flexibility', trend: 'positive' },
        { driver: 'Core EPS', impact: 'Strong FCF/EPS quality underpins credit profile', trend: 'positive' },
      ]),
    },
    {
      title: 'Regulatory Risk — PMDA/FDA/EMA Multi-Market Approval Dependencies for Strategic Brands',
      category: 'Risk & Compliance',
      insightLevel: 'L2',
      metricId: 'R&D Pipeline Value',
      kpiValue: 'VYLOY US PDUFA under review; PADCEV EU first-line sNDA filed; VEOZAH EU ongoing',
      trendDirection: 'neutral',
      priority: 'high',
      summary: 'Astellas has multiple near-term regulatory milestones that significantly impact Strategic Brands FY26 revenue guidance: (1) VYLOY US FDA PDUFA date under review for gastric cancer — US approval is the largest single catalytic event (estimated ¥30–40B FY26 US revenue contribution); (2) PADCEV EU first-line mUC sNDA filed with EMA — EU label expansion supports Established Markets growth; (3) VEOZAH US supplemental NDA for perimenopause indication in review — could expand the addressable patient population. Regulatory setbacks in any of these would create downside to FY26 guidance, though the SMT savings buffer provides partial financial offset.',
      confidenceScore: 0.82,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Maintain quarterly regulatory milestones table in investor materials with PDUFA dates, filing status, and estimated revenue impact of approval',
        'Communicate VYLOY US PDUFA uncertainty range clearly — the PDUFA date uncertainty is the largest near-term binary risk in FY26 guidance',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'R&D Pipeline Value', impact: 'VYLOY US, PADCEV EU, VEOZAH US key FY26 catalysts', trend: 'positive' },
        { driver: 'Strategic Brands Revenue', impact: 'Regulatory approvals unlock FY26 guidance achievement', trend: 'positive' },
      ]),
    },
    {
      title: 'Governance — Shareholder Alignment; CEO Okamura\'s Mid-Term Management Plan Delivery Tracking',
      category: 'Risk & Compliance',
      insightLevel: 'L2',
      metricId: 'Core EPS',
      kpiValue: 'Mid-Term Management Plan FY24-FY26: Core EPS ¥248-255 target; Strategic Brands ¥610B+ target',
      trendDirection: 'up',
      priority: 'medium',
      summary: 'CEO Naoki Okamura\'s Mid-Term Management Plan (FY24–FY26) has 4 primary financial targets: (1) Core EPS ¥248–¥255 by FY26 (tracking well, FY25 ¥237); (2) Strategic Brands revenue ¥610B+ (FY25 ¥480.3B, on track for ¥610–640B FY26); (3) Core OP margin 27–28% FY26 (FY25 26.0%, SMT Phase 2 needed); (4) FCF ¥480B+ annually (FY25 ¥520.8B, above target). Management incentive compensation is tied to these KPIs, ensuring alignment with the shareholder value framework. FY25 performance vs. plan supports a positive interim delivery assessment ahead of the planned FY26 Mid-Term Plan completion review.',
      confidenceScore: 0.88,
      consoleLink: '/business-consoles/financial-performance',
      recommendations: [
        'Publish a Mid-Term Plan progress scorecard in the FY25 Annual Report — formal tracking of the 4 primary financial targets vs. actuals builds investor confidence',
        'Disclose management compensation linkage to Mid-Term Plan metrics to demonstrate governance alignment',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Core EPS', impact: 'FY25 ¥237 tracking toward ¥248-255 FY26 target', trend: 'positive' },
        { driver: 'Strategic Brands Revenue', impact: 'FY25 ¥480B tracking toward ¥610B+ FY26 target', trend: 'positive' },
      ]),
    },
    {
      title: 'ESG — Science-Based Emission Targets; Portfolio Contribution to Unmet Medical Need',
      category: 'Risk & Compliance',
      insightLevel: 'L2',
      metricId: 'Total Revenue',
      kpiValue: 'SBTi validated net-zero pathway by 2040; 90%+ portfolio revenue in unmet or high-need indications',
      trendDirection: 'neutral',
      priority: 'medium',
      summary: 'Astellas maintains Science-Based Targets initiative (SBTi) validation for its net-zero greenhouse gas emissions pathway by 2040. Manufacturing GHG emissions declined 8.5% YoY in FY25 (Scope 1+2 combined) as renewable energy procurement expanded at manufacturing sites. The portfolio is concentrated in oncology and rare disease indications where unmet medical need is high — approximately 90%+ of revenue is in indications classified as high unmet need by FDA/EMA. ESG-focused institutional investors (representing approximately 35% of the ALPMY register) view the oncology/rare disease focus and SBTi pathway positively relative to diversified pharma peers.',
      confidenceScore: 0.82,
      consoleLink: '/business-consoles/enterprise-risk',
      recommendations: [
        'Quantify ESG progress in shareholder communications: GHG reduction %, patient access programme reach, diversity metrics — ESG disclosure quality is increasingly important for institutional investors',
        'Highlight portfolio unmet need concentration as a governance and ESG attribute, not just a commercial strategy',
      ],
      relatedDrivers: JSON.stringify([
        { driver: 'Total Revenue', impact: '90%+ revenue in unmet medical need; ESG-aligned portfolio', trend: 'positive' },
        { driver: 'R&D Pipeline Value', impact: 'Oncology/rare disease focus maximises ESG portfolio quality', trend: 'positive' },
      ]),
    },

  ];

  let count = 0;
  for (const insight of insights) {
    await prisma.personalizedInsight.create({
      data: {
        companyId,
        title: insight.title,
        category: insight.category,
        insightLevel: insight.insightLevel,
        metricId: insight.metricId,
        kpiValue: insight.kpiValue,
        trendDirection: insight.trendDirection,
        priority: insight.priority,
        summary: insight.summary,
        confidenceScore: insight.confidenceScore,
        consoleLink: insight.consoleLink,
        recommendations: insight.recommendations as unknown as any,
        relatedDrivers: insight.relatedDrivers as unknown as any,
      },
    });
    count++;
  }

  console.log(`  Seeded ${count} Astellas Pharma expanded insights (FY25 full coverage)`);
}
