import {
    BarChart3,
    Calendar,
    Clock,
    Building2,
    DollarSign,
    Globe,
    Landmark,
    PieChart,
    Scale,
    Target,
    Users,
} from 'lucide-react';

import type { PersonalizedInsight } from './search-types';

// ── Personalized Insights (Delta Finance360 / CFO scoreboard aligned) ─────────
// IDs are stable — HomeTileSection + CFOTiles reference these for modal detail.

export const personalizedInsights: PersonalizedInsight[] = [
    {
        id: 1,
        title: 'XTANDI US Net Revenue: ¥960.8B FY25',
        kpi: '¥960.8B',
        kpiLabel: 'XTANDI global revenue (FY25)',
        insight: 'Astellas XTANDI (enzalutamide) delivered ¥960.8B in FY25 global revenue — the largest product in the portfolio at ~45% of total revenue. US market leadership in prostate cancer (mCRPC, nmCRPC, mCSPC, nmCSPC) drives the majority of XTANDI revenue. IRA price negotiation effective 2026 is the primary near-term risk to this trajectory.',
        trend: 'up',
        value: '~45% of total revenue',
        priority: 'high',
        icon: Globe,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#D91E49]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'XTANDI Franchise',
        confidenceScore: 97,
        dataSource: 'Astellas Annual Securities Report FY2025 + Q1 FY26 Earnings',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Monitor IRA Maximum Fair Price negotiation timeline — CMS announcement expected Q3 2025 sets the FY26 revenue floor',
            'Track XTANDI US market share vs. ERLEADA (apalutamide) in nmCSPC — competitive overlap is the primary share risk',
            'Quantify XTANDI label expansion opportunity in earlier disease states (low-risk nmCSPC) to expand non-IRA-negotiated revenue base',
        ],
        impactedMetrics: [
            { metric: 'XTANDI global revenue (FY25)', value: '¥960.8B', trend: 'positive' },
            { metric: 'XTANDI US market share (prostate cancer)', value: '~40%', trend: 'positive' },
            { metric: 'IRA MFP sensitivity (per 5% discount)', value: '~¥30B Core OP impact', trend: 'negative' },
        ],
        historicalContext: 'XTANDI global revenue grew from ~¥600B (FY2020) to ¥960.8B (FY2025), reflecting label expansions across all prostate cancer disease states and Pfizer co-promote transition. IRA negotiation marks the end of unconstrained US pricing growth.',
        predictiveInsight: 'XTANDI US revenue trajectory depends critically on the IRA MFP outcome — a 15% MFP discount vs. WAC creates a ~¥60B annual headwind, partially offset by volume growth in non-Medicare populations and label expansions.',
        dataQuality: 'Very High',
        modelAccuracy: '96%',
        consoleLink: '/business-consoles/xtandi-franchise',
        consoleAvailable: true,
    },
    {
        id: 2,
        title: 'Core OP: ¥555.7B (26% Margin)',
        kpi: '¥555.7B',
        kpiLabel: 'Core Operating Income FY25 (26% margin)',
        insight: 'Astellas Core Operating Income of ¥555.7B in FY25 represents a 26% Core OP margin — the highest in the company\'s history, driven by XTANDI/PADCEV volume leverage and SMT savings delivering ¥21B ahead of the ¥40B FY26 target. Sustaining this margin through IRA and Japan NHI headwinds is the central FY26 management challenge.',
        trend: 'up',
        value: '+26% Core OP margin',
        priority: 'high',
        icon: Target,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#D91E49]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Financial Performance',
        confidenceScore: 94,
        dataSource: 'Astellas Annual Securities Report FY2025 + Q1 FY26 Earnings Supplement',
        lastUpdated: '4 hours ago',
        aiRecommendations: [
            'Confirm SMT ¥40B FY26 savings delivery timeline — workstream tracking is critical to margin guidance maintenance',
            'Monitor Core OP margin sensitivity to IRA XTANDI headwind: each ¥30B revenue impact ≈ ~140bps margin compression at current scale',
            'Track Core OP margin vs. peer benchmarks: AstraZeneca ~28%, J&J Pharma ~30% — Astellas 26% has upside through SMT delivery',
        ],
        impactedMetrics: [
            { metric: 'Core Operating Income FY25', value: '¥555.7B', trend: 'positive' },
            { metric: 'Core OP margin FY25', value: '26%', trend: 'positive' },
            { metric: 'SMT savings delivered FY25', value: '¥21B', trend: 'positive' },
        ],
        historicalContext: 'Astellas Core OP margin expanded from ~22% (FY2020) to 26% (FY2025) as XTANDI and PADCEV scale created operating leverage over SG&A. SMT program is the structural efficiency driver for FY26+ margin defense.',
        predictiveInsight: 'At 26% Core OP margin with ¥40B SMT savings in FY26, Astellas is positioned to defend 24-26% margin even under combined IRA (-¥60B) and Japan NHI (-¥26B) headwinds, provided volume growth in emerging products offsets.',
        dataQuality: 'High',
        modelAccuracy: '91%',
        consoleLink: '/business-consoles/financial-performance',
        consoleAvailable: true,
    },
    {
        id: 3,
        title: 'Core EPS ¥237 FY25',
        kpi: '¥237',
        kpiLabel: 'Core EPS FY25 (vs ¥200 FY24)',
        insight: 'Core EPS of ¥237 in FY25 represents ~18.5% YoY growth from ¥200 in FY24 — driven by XTANDI/PADCEV revenue growth, SMT savings, and disciplined capital allocation. FY26 guidance of ¥230-250 reflects headwinds from IRA XTANDI negotiation and Japan NHI revision partially offset by PADCEV/VEOZAH growth.',
        trend: 'up',
        value: '+18.5% YoY',
        priority: 'medium',
        icon: DollarSign,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#D91E49]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Financial Performance',
        confidenceScore: 95,
        dataSource: 'Astellas Annual Securities Report FY2025 Earnings Statement',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Bridge FY26 Core EPS guidance from FY25 ¥237 base: IRA headwind -¥10, Japan NHI -¥5, PADCEV/VEOZAH growth +¥15, SMT +¥8',
            'Separate IRA timing impact from structural Core EPS trajectory in investor communications',
            'Highlight Core EPS sensitivity: +1% XTANDI US volume ≈ +¥2 Core EPS; +¥1 USD/JPY ≈ +¥0.3 Core EPS',
        ],
        impactedMetrics: [
            { metric: 'Core EPS FY25', value: '¥237 (+18.5% YoY)', trend: 'positive' },
            { metric: 'Core Operating Income FY25', value: '¥555.7B', trend: 'positive' },
            { metric: 'Core EPS FY26 guidance', value: '¥230-250', trend: 'stable' },
        ],
        historicalContext: 'Astellas Core EPS has grown from ~¥130 (FY2020) to ¥237 (FY2025), reflecting the XTANDI/PADCEV revenue compounding and SMT transformation — a structural earnings growth story entering a new IRA-constrained phase.',
        predictiveInsight: 'FY26 Core EPS trajectory will be determined by the XTANDI IRA MFP outcome (announced mid-2025) and Japan NHI revision (-6.5% est.) — management has guided ¥230-250 reflecting the combined headwind scenario.',
        dataQuality: 'Very High',
        modelAccuracy: '95%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 4,
        title: 'SMT Transformation: ¥21B FY25 Savings',
        kpi: '¥21B',
        kpiLabel: 'FY25 SMT savings delivered (target ¥40B FY26)',
        insight: 'Astellas\'s Strategic Management Transformation (SMT) program delivered ¥21B in FY25 savings — ahead of the original ¥18B target, and on track toward the ¥40B FY26 goal. Key workstreams include commercial model transformation (digital HCP engagement), procurement savings, shared services, and manufacturing optimization.',
        trend: 'up',
        value: '¥40B FY26 target',
        priority: 'high',
        icon: Users,
        bgColor: 'bg-indigo-50',
        iconColor: 'text-indigo-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'SMT Transformation',
        confidenceScore: 90,
        dataSource: 'Astellas SMT Program Update + Q1 FY26 Earnings Supplement',
        lastUpdated: '30 minutes ago',
        aiRecommendations: [
            'Track Q1 FY26 SMT savings run-rate vs ¥10B quarterly target — front-half delivery is critical to FY26 full-year achievement',
            'Monitor digital HCP engagement adoption rate — primary commercial model transformation metric enabling SG&A savings',
            'Confirm SMT workstream timelines: shared services consolidation and manufacturing process optimization are key FY26 contributors',
        ],
        impactedMetrics: [
            { metric: 'SMT savings FY25 actual', value: '¥21B (ahead of ¥18B target)', trend: 'positive' },
            { metric: 'SMT savings FY26 target', value: '¥40B', trend: 'positive' },
            { metric: 'Core SG&A as % of revenue', value: 'Declining toward 25%', trend: 'positive' },
        ],
        historicalContext: 'Astellas launched SMT in FY23 with a ¥100B cumulative savings target through FY28. FY25 ¥21B delivery ahead of schedule demonstrates execution capability — the FY26 ¥40B target requires a step-change acceleration in digital commercial adoption.',
        predictiveInsight: 'Each ¥5B of SMT savings delivered above FY26 target translates to approximately +¥3 Core EPS uplift — making SMT the most controllable earnings driver in the near-term planning horizon.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/business-consoles/smt-transformation',
        consoleAvailable: true,
    },
    {
        id: 5,
        title: 'PADCEV FY25 Revenue ¥221.2B (+40% YoY)',
        kpi: '¥221.2B',
        kpiLabel: 'PADCEV global revenue FY25 (+~40% YoY)',
        insight: 'PADCEV (enfortumab vedotin) delivered ¥221.2B in FY25 — up approximately 40% YoY — driven by first-line bladder cancer standard-of-care adoption following EV-302/KEYNOTE-A39 landmark data. PADCEV is Astellas\'s second-largest product and the fastest-growing franchise, with manufacturing scale-up capacity being the primary constraint on further volume growth.',
        trend: 'up',
        value: '~40% YoY growth',
        priority: 'high',
        icon: Building2,
        bgColor: 'bg-teal-50',
        iconColor: 'text-teal-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'PADCEV Franchise',
        confidenceScore: 93,
        dataSource: 'Astellas Annual Securities Report FY2025 + PADCEV Commercial Update',
        lastUpdated: '15 minutes ago',
        aiRecommendations: [
            'Accelerate PADCEV biologics manufacturing capacity — current supply fill rate ~72% constrains addressable revenue by ¥20-30B annually',
            'Monitor PADCEV first-line bladder cancer market share trajectory — target >50% by FY27 from ~40% FY25',
            'Track PADCEV EU launch rollout — European reimbursement decisions are the next major revenue expansion catalyst',
        ],
        impactedMetrics: [
            { metric: 'PADCEV global revenue FY25', value: '¥221.2B (~+40% YoY)', trend: 'positive' },
            { metric: 'PADCEV first-line bladder cancer share', value: '~40% US', trend: 'positive' },
            { metric: 'PADCEV manufacturing capacity utilization', value: '~72% of demand', trend: 'positive' },
        ],
        historicalContext: 'PADCEV launched FY2021 in second-line bladder cancer; EV-302 first-line data (2023) transformed the commercial trajectory, creating the current 40%+ growth rate from a much larger addressable patient population.',
        predictiveInsight: 'Closing the 28% manufacturing capacity gap could add ¥15-25B in incremental annual PADCEV revenue — making manufacturing investment the highest-ROIC capital allocation decision for FY26-FY27.',
        dataQuality: 'High',
        modelAccuracy: '90%',
        consoleLink: '/business-consoles/padcev-commercial',
        consoleAvailable: true,
    },
    {
        id: 6,
        title: 'Japan NHI Revision Risk: -6.5%',
        kpi: '-6.5%',
        kpiLabel: 'Japan NHI biennial price revision (April 2026 est.)',
        insight: 'Japan\'s April 2026 biennial NHI drug price revision is estimated at -6.5% on Astellas\'s Japan portfolio — creating a ~¥26B revenue headwind. XTANDI, PADCEV, and legacy oncology products are all subject to the revision. VYLOY Japan launch and volume growth in existing products are designed to partially offset the pricing compression.',
        trend: 'down',
        value: '~¥26B revenue headwind',
        priority: 'high',
        icon: Globe,
        bgColor: 'bg-red-50',
        iconColor: 'text-[#D91E49]',
        valueColor: 'text-red-600',
        action: 'View Details',
        category: 'Japan Operations',
        confidenceScore: 89,
        dataSource: 'MHLW Drug Pricing Review + Astellas Japan Segment Analysis',
        lastUpdated: '3 hours ago',
        aiRecommendations: [
            'Model Japan segment FY26 revenue at -5% (favorable) and -8% (adverse) NHI scenarios for Board risk committee',
            'Accelerate VYLOY Japan commercial launch to offset revision headwind — each ¥5B VYLOY revenue is ~20% of headwind',
            'Develop Japan portfolio volume growth strategy to ensure patient volume expansion absorbs per-unit price reductions',
        ],
        impactedMetrics: [
            { metric: 'Japan NHI revision rate estimate (April 2026)', value: '-6.5%', trend: 'negative' },
            { metric: 'Japan segment revenue FY25', value: '~¥380B', trend: 'stable' },
            { metric: 'Japan NHI revision revenue headwind', value: '~¥26B annual', trend: 'negative' },
        ],
        historicalContext: 'Japan NHI biennial revision has averaged -5% to -7% over the past decade. The FY26 revision is expected at the wider end (-6.5%) as MHLW prioritizes pricing sustainability for the national healthcare budget amid aging demographics.',
        predictiveInsight: 'Japan segment revenue returns to positive growth in FY27 (non-revision year) as VYLOY ramp, XTANDI volume expansion, and new product launches overcome the FY26 revision baseline.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/business-consoles/japan-segment',
        consoleAvailable: true,
    },
    {
        id: 7,
        title: 'IRA XTANDI Negotiation — MFP Risk',
        kpi: '¥30-80B',
        kpiLabel: 'IRA headwind range (5-15% MFP discount scenarios)',
        insight: 'CMS has selected XTANDI for Medicare Part D price negotiation under the Inflation Reduction Act. The Maximum Fair Price effective from January 2026 creates an irreversible US net revenue reduction. Astellas management is engaged with CMS and has guided a ¥30-80B potential annual revenue impact depending on the negotiated MFP level. Volume growth in non-Medicare US populations and label expansions are the primary offsets.',
        trend: 'down',
        value: 'MFP effective Jan 2026',
        priority: 'high',
        icon: Landmark,
        bgColor: 'bg-orange-50',
        iconColor: 'text-orange-700',
        valueColor: 'text-red-600',
        action: 'View Details',
        category: 'US Regulatory',
        confidenceScore: 85,
        dataSource: 'CMS IRA Negotiation Program + Astellas Q1 FY26 Earnings Commentary',
        lastUpdated: '10 minutes ago',
        aiRecommendations: [
            'Build FY26 revenue model at ¥30B (best case), ¥55B (base), and ¥80B (adverse) IRA headwind scenarios',
            'Track XTANDI label expansion progress — earlier-stage nmCSPC patients are largely non-Medicare, limiting IRA exposure growth',
            'Monitor peer drug MFP negotiation outcomes (Eliquis, Jardiance) as benchmarks for expected XTANDI discount range',
        ],
        impactedMetrics: [
            { metric: 'XTANDI IRA negotiation headwind (base)', value: '~¥55B annual FY26', trend: 'negative' },
            { metric: 'XTANDI Medicare Part D revenue share', value: '~35-40% of US revenue', trend: 'stable' },
            { metric: 'XTANDI non-Medicare US revenue (insulated)', value: '~60-65% of US', trend: 'positive' },
        ],
        historicalContext: 'XTANDI was among the 10 drugs selected in the first IRA negotiation cycle. The statutory MFP framework limits CMS pricing authority but creates a precedent-setting initial negotiation that Astellas has engaged in constructively.',
        predictiveInsight: 'Post-MFP effective date, XTANDI US revenue trajectory shifts from price × volume to primarily volume-driven growth — making patient share and label expansion the dominant earnings levers in the US market from FY26 onward.',
        dataQuality: 'Medium',
        modelAccuracy: '82%',
        consoleLink: '/business-consoles/us-regulatory',
        consoleAvailable: true,
    },
    {
        id: 8,
        title: 'FX Sensitivity: ¥2.1B per ¥1 USD/JPY',
        kpi: '¥2.1B',
        kpiLabel: 'Core OP sensitivity per ¥1 USD/JPY rate move',
        insight: 'Astellas reports in Japanese yen with ~60% of revenue generated in USD and EUR. Each ¥1 USD/JPY rate move creates a ¥2.1B Core OP impact annually — with USD/JPY currently at ~¥150, a BoJ-driven appreciation to ¥140 would create a ¥21B Core OP headwind. Astellas hedges approximately 50% of annual FX exposure through forward contracts.',
        trend: 'flat',
        value: '~50% FX hedged',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-blue-50',
        iconColor: 'text-blue-700',
        valueColor: 'text-amber-600',
        action: 'View Details',
        category: 'FX & Treasury',
        confidenceScore: 91,
        dataSource: 'Astellas Annual Securities Report FY2025 + FX Sensitivity Disclosure',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Maintain Astellas downside scenario at USD/JPY ¥140: ¥21B Core OP headwind on unhedged exposure',
            'Bridge USD/JPY sensitivity to Core EPS: each ¥1 move ≈ ¥0.3 Core EPS on current share count',
            'Evaluate FX hedging program extension to 18-month rolling coverage to reduce quarterly earnings volatility',
        ],
        impactedMetrics: [
            { metric: 'Core OP FX sensitivity', value: '¥2.1B per ¥1 USD/JPY', trend: 'stable' },
            { metric: 'USD revenue base (XTANDI US)', value: '~¥570B annually', trend: 'positive' },
            { metric: 'FX hedging coverage ratio', value: '~50% of annual exposure', trend: 'stable' },
        ],
        historicalContext: 'Astellas FX sensitivity has grown as XTANDI US revenue has scaled from ¥200B (FY2018) to ¥570B (FY2025) — the USD/JPY rate has become one of the most material single variables in Astellas\'s reported financial performance.',
        predictiveInsight: 'Bank of Japan monetary policy normalization (rate hikes) is the primary structural risk to sustained USD/JPY above ¥150 — if JPY appreciates to ¥130, unhedged annual FX headwind reaches ¥42B on current revenue base.',
        dataQuality: 'High',
        modelAccuracy: '92%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 9,
        title: 'VEOZAH US Launch Ramp',
        kpi: '~¥25-30B',
        kpiLabel: 'VEOZAH FY25 US revenue (launch ramp)',
        insight: 'VEOZAH (fezolinetant) US launch is building through OB/GYN and women\'s health prescriber networks — reaching approximately 19% active prescriber adoption by end-FY25. The ~25,000 addressable US prescriber base provides significant runway. Weekly prescription growth is tracking above plan with strong patient satisfaction scores supporting refill rates.',
        trend: 'up',
        value: 'Top-quartile launch trajectory',
        priority: 'medium',
        icon: Users,
        bgColor: 'bg-green-50',
        iconColor: 'text-green-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Emerging Products',
        confidenceScore: 85,
        dataSource: 'Astellas VEOZAH Commercial Update + IQVIA Prescription Data',
        lastUpdated: '45 minutes ago',
        aiRecommendations: [
            'Link VEOZAH prescriber adoption to revenue ramp — target 28% prescriber adoption by Q2 FY26 to sustain above-plan trajectory',
            'Quantify DTC campaign ROI for VEOZAH — patient-initiated demand is a key differentiator from HRT alternatives',
            'Track VEOZAH refill rate as a leading indicator of patient satisfaction and net revenue per patient',
        ],
        impactedMetrics: [
            { metric: 'VEOZAH active prescriber adoption', value: '~19% of addressable US OB/GYN', trend: 'positive' },
            { metric: 'VEOZAH weekly TRx growth (FY25 Q4)', value: '+45% YoY', trend: 'positive' },
            { metric: 'VEOZAH patient refill rate', value: '>65%', trend: 'positive' },
        ],
        historicalContext: 'VEOZAH launched FY2024 as the first non-hormonal, central mechanism treatment for vasomotor symptoms — addressing a large underserved women\'s health market where HRT alternatives were the only options.',
        predictiveInsight: 'VEOZAH prescriber adoption reaching 40%+ by FY27 could support ¥50-80B annual revenue — creating a meaningful third product franchise alongside XTANDI and PADCEV in Astellas\'s portfolio.',
        dataQuality: 'Medium',
        modelAccuracy: '83%',
        consoleLink: '/business-consoles/veozah-launch',
        consoleAvailable: true,
    },
    {
        id: 10,
        title: 'IZERVAY Geographic Atrophy Market Build',
        kpi: '~21%',
        kpiLabel: 'IZERVAY US GA market share (FY25)',
        insight: 'IZERVAY (avacincaptad pegol) is building US market share in geographic atrophy — a rare degenerative retinal condition. With ~21% GA market share at end-FY25 alongside Syfovre (Apellis) competition, IZERVAY\'s differentiated monthly dosing profile and strong visual acuity outcomes are gaining traction with retinal specialists. FDA label expansion discussions for dry AMD are underway.',
        trend: 'up',
        value: 'Monthly dosing advantage',
        priority: 'medium',
        icon: Target,
        bgColor: 'bg-purple-50',
        iconColor: 'text-purple-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Emerging Products',
        confidenceScore: 84,
        dataSource: 'Astellas IZERVAY Commercial Update + Retinal Specialist Market Data',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Build IZERVAY retinal specialist coverage — target >80% key account coverage to defend against Syfovre competitive pressure',
            'Advance FDA discussions on dry AMD label expansion — broader label would 5x the addressable patient population',
            'Track IZERVAY real-world visual acuity outcomes data — patient outcomes evidence is critical for payer formulary positioning',
        ],
        impactedMetrics: [
            { metric: 'IZERVAY US GA market share', value: '~21%', trend: 'positive' },
            { metric: 'IZERVAY monthly dosing adoption rate', value: '>75% of prescribers', trend: 'positive' },
            { metric: 'Dry AMD label expansion (potential)', value: '5x patient population expansion', trend: 'positive' },
        ],
        historicalContext: 'IZERVAY launched in the US in FY2024 as the second complement-targeting GA therapy after Apellis Syfovre. Monthly vs. every-other-month dosing is the key product differentiator driving prescriber preference in the retinal specialist community.',
        predictiveInsight: 'FDA approval of IZERVAY for dry AMD beyond GA could represent the largest single label expansion opportunity in Astellas\'s portfolio — potentially adding ¥50-100B in annual revenue at peak penetration.',
        dataQuality: 'Medium',
        modelAccuracy: '82%',
        consoleLink: '/business-consoles/izervay-commercial',
        consoleAvailable: true,
    },
    {
        id: 11,
        title: 'VYLOY Japan NHI Listing Pipeline',
        kpi: 'H2 FY26',
        kpiLabel: 'VYLOY Japan NHI listing timeline (est.)',
        insight: 'VYLOY (zolbetuximab) received Japan PMDA approval for CLDN18.2-positive gastric cancer in FY25 and is pending NHI listing (expected H2 FY26). SPOTLIGHT and GLOW Phase 3 data supporting first-line use in combination with chemotherapy positions VYLOY as an important addition to Astellas\'s Japan oncology portfolio, partially offsetting NHI revision headwinds.',
        trend: 'up',
        value: 'Japan approval secured',
        priority: 'medium',
        icon: PieChart,
        bgColor: 'bg-amber-50',
        iconColor: 'text-amber-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Japan Operations',
        confidenceScore: 88,
        dataSource: 'Astellas VYLOY Development Update + PMDA Approval Announcement',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Track MHLW NHI listing review timeline — Q3 FY26 NHI listing would enable Q4 FY26 commercial launch to offset revision headwind',
            'Develop CLDN18.2 biomarker testing deployment strategy — testing adoption rate is the critical gating factor for patient identification',
            'Model VYLOY Japan launch scenario at ¥5B (conservative) and ¥15B (base case) FY26 revenue contribution',
        ],
        impactedMetrics: [
            { metric: 'VYLOY Japan approval status', value: 'PMDA approved FY25', trend: 'positive' },
            { metric: 'VYLOY Japan NHI listing (expected)', value: 'H2 FY26', trend: 'positive' },
            { metric: 'CLDN18.2-positive gastric cancer market (Japan)', value: '~8,000 patients/year', trend: 'positive' },
        ],
        historicalContext: 'Astellas filed VYLOY for Japan approval following SPOTLIGHT (1L gastric cancer) and GLOW (1L gastroesophageal junction) Phase 3 success. Japan is the largest gastric cancer market globally, making VYLOY a strategically important new product for the Japan franchise.',
        predictiveInsight: 'VYLOY peak Japan revenue of ¥30-50B by FY28 is achievable if CLDN18.2 biomarker testing adoption reaches 60%+ in gastric cancer patients — making testing infrastructure investment a key commercial prerequisite.',
        dataQuality: 'High',
        modelAccuracy: '85%',
        consoleLink: '/business-consoles/japan-segment',
        consoleAvailable: true,
    },
    {
        id: 12,
        title: 'Established Markets Revenue: ~¥280B',
        kpi: '~¥280B',
        kpiLabel: 'Established Markets FY25 revenue (~+5% YoY)',
        insight: 'Astellas Established Markets (Europe, Australia, Canada) segment delivered ~¥280B in FY25 revenue (+~5% YoY), driven by XTANDI market penetration in earlier prostate cancer disease states, PADCEV European reimbursement rollout, and VEOZAH EU market preparation. EUR/JPY FX translation creates variability in yen-reported growth rates.',
        trend: 'up',
        value: '~+5% YoY growth',
        priority: 'medium',
        icon: Scale,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#D91E49]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Established Markets',
        confidenceScore: 89,
        dataSource: 'Astellas Segment Reporting FY2025 + Established Markets Update',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Accelerate PADCEV EU reimbursement coverage — Health Technology Assessment outcomes are the critical revenue gate',
            'Model EUR/JPY sensitivity: each ¥1 EUR/JPY move ≈ ¥0.9B Core OP impact on Established Markets base',
            'Develop XTANDI European market share defense strategy vs. ERLEADA in markets where nmCSPC reimbursement is broader',
        ],
        impactedMetrics: [
            { metric: 'Established Markets revenue FY25', value: '~¥280B (+~5% YoY)', trend: 'positive' },
            { metric: 'PADCEV EU reimbursement status', value: 'Rolling rollout Q3 FY26', trend: 'positive' },
            { metric: 'XTANDI European market share', value: '~35% mCRPC', trend: 'stable' },
        ],
        historicalContext: 'Established Markets have grown from ~¥200B (FY2020) toward ¥280B (FY2025) as XTANDI European label expansions and PADCEV launches build the franchise — EUR/JPY has been a significant volatility driver in yen-reported terms.',
        predictiveInsight: 'Established Markets can reach ¥320-350B by FY27 if PADCEV EU reimbursement rollout achieves 50%+ market access coverage and XTANDI holds >30% European prostate cancer share through label breadth.',
        dataQuality: 'High',
        modelAccuracy: '87%',
        consoleLink: '/business-consoles/established-markets',
        consoleAvailable: true,
    },
    {
        id: 13,
        title: 'FY25 Total Revenue: ¥2,139.2B',
        kpi: '¥2,139.2B',
        kpiLabel: 'FY25 total revenue (guidance ¥2,150-2,250B for FY26)',
        insight: 'Astellas reported FY25 total revenue of ¥2,139.2B, anchored by XTANDI (¥960.8B), PADCEV (¥221.2B), and contributions from Japan segment, Established Markets, and emerging launches. FY26 guidance of ¥2,150-2,250B reflects IRA and Japan NHI headwinds offset by PADCEV/VEOZAH growth and SMT-driven efficiency improvements.',
        trend: 'up',
        value: 'FY26 guidance ¥2,150-2,250B',
        priority: 'high',
        icon: Clock,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-emerald-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Financial Performance',
        confidenceScore: 94,
        dataSource: 'Astellas Annual Securities Report FY2025 + FY26 Initial Guidance',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Stress-test FY26 revenue guidance at bear case: XTANDI IRA -¥80B + Japan NHI -¥30B + PADCEV shortfall -¥20B = ~¥2,010B floor',
            'Model upside scenario: +PADCEV volume growth above plan + VEOZAH ramp + VYLOY Japan = ¥2,300B+ ceiling',
            'Align revenue growth narrative with Core OP margin guidance — revenue must grow above ¥2,100B to defend 25%+ margin',
        ],
        impactedMetrics: [
            { metric: 'Total revenue FY25', value: '¥2,139.2B', trend: 'positive' },
            { metric: 'Revenue FY26 guidance', value: '¥2,150-2,250B', trend: 'positive' },
            { metric: 'Revenue ex-XTANDI FY25', value: '~¥1,178B (+~15% YoY)', trend: 'positive' },
        ],
        historicalContext: 'Astellas revenue has grown from ~¥1,300B (FY2020) to ¥2,139.2B (FY2025) — XTANDI doubled in 5 years while the non-XTANDI portfolio (PADCEV, VEOZAH, Japan) has grown to represent 55% of total revenue.',
        predictiveInsight: 'Revenue diversification beyond XTANDI is the structural story for FY26+: if PADCEV, VEOZAH, IZERVAY, and VYLOY collectively grow ¥150B, they offset the combined IRA + NHI headwinds, supporting total revenue growth.',
        dataQuality: 'Very High',
        modelAccuracy: '94%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 14,
        title: 'Oncology Pipeline: R&D Investment',
        kpi: '~¥220B',
        kpiLabel: 'FY25 R&D expense (~10% of revenue)',
        insight: 'Astellas invests ~¥220B annually in R&D (~10% of FY25 revenue), focused on oncology (prostate, bladder, gastric, hematology), gene therapy, and women\'s health. The pipeline includes 20+ Phase 2/3 assets, with near-term catalysts in PADCEV new combinations, XTANDI label expansion studies, and gene therapy programs from the acquired Audentes/Ambys portfolio.',
        trend: 'up',
        value: '20+ Phase 2/3 assets',
        priority: 'medium',
        icon: BarChart3,
        bgColor: 'bg-green-50',
        iconColor: 'text-green-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'R&D Pipeline',
        confidenceScore: 88,
        dataSource: 'Astellas R&D Day Presentation + Annual Securities Report FY2025',
        lastUpdated: '4 hours ago',
        aiRecommendations: [
            'Prioritize PADCEV combination studies as highest near-term R&D value — combinations in new indications extend product lifecycle',
            'Track ASP-2151 Phase 3 progression — gene therapy program with blockbuster potential if clinical success is demonstrated',
            'Model R&D productivity through Phase 3 advancement rate: ~68% FY25 success rate supports 20+ Phase 2/3 pipeline conversion',
        ],
        impactedMetrics: [
            { metric: 'R&D expense FY25', value: '~¥220B (~10% of revenue)', trend: 'stable' },
            { metric: 'Phase 2/3 pipeline assets', value: '20+', trend: 'positive' },
            { metric: 'R&D Phase 3 advancement success rate', value: '~68% FY25', trend: 'positive' },
        ],
        historicalContext: 'Astellas R&D investment has sustained at 9-11% of revenue consistently — the strategic shift from broad therapeutic areas to focused oncology + gene therapy is improving R&D productivity metrics from the legacy 60% Phase 3 success rate.',
        predictiveInsight: 'R&D pipeline maturation through FY27-FY28 could deliver 2-3 new product approvals beyond VYLOY and IZERVAY — gene therapy and next-generation oncology assets represent the future revenue diversification beyond the current product suite.',
        dataQuality: 'High',
        modelAccuracy: '85%',
        consoleLink: '/business-consoles/pipeline-rd',
        consoleAvailable: true,
    },
    {
        id: 15,
        title: 'US Segment Revenue: ~45% of Total',
        kpi: '~45%',
        kpiLabel: 'US segment % of Astellas total revenue (FY26E)',
        insight: 'Astellas US segment represents approximately 45% of total revenue (~¥960B), driven almost entirely by XTANDI and the rapidly growing PADCEV/VEOZAH/IZERVAY emerging product suite. IRA price negotiation on XTANDI and the post-Pfizer co-promote transition make the US segment both Astellas\'s largest revenue driver and its most concentrated external risk.',
        trend: 'up',
        value: '+PADCEV/VEOZAH growth',
        priority: 'medium',
        icon: Globe,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-emerald-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'US Operations',
        confidenceScore: 92,
        dataSource: 'Astellas US Segment Reporting FY2025 + Q1 FY26 Earnings',
        lastUpdated: '3 hours ago',
        aiRecommendations: [
            'Highlight US segment IRA concentration risk: ~45% of revenue in a single geography under active price negotiation',
            'Model blended US revenue growth from PADCEV/VEOZAH/IZERVAY: each ¥20B emerging product revenue = ~1% of total revenue',
            'Refresh US segment mix post-FY26 with XTANDI IRA impact fully embedded into revised revenue structure',
        ],
        impactedMetrics: [
            { metric: 'US segment revenue share (FY26E)', value: '~45%', trend: 'positive' },
            { metric: 'XTANDI share of US segment', value: '~60%', trend: 'stable' },
            { metric: 'PADCEV/VEOZAH/IZERVAY US combined', value: '~¥300B and growing', trend: 'positive' },
        ],
        historicalContext: 'US segment share has grown from ~38% (FY2020) toward 45% (FY2025) as XTANDI US revenue outpaced Japan and Established Markets growth. IRA and competitive dynamics create the ceiling on further US concentration.',
        predictiveInsight: 'Post-IRA normalization (FY27+), US segment growth shifts to PADCEV and emerging products — a healthier, more diversified revenue profile that reduces XTANDI single-product concentration risk.',
        dataQuality: 'Very High',
        modelAccuracy: '93%',
        consoleLink: '/business-consoles/us-commercial',
        consoleAvailable: true,
    },
];
